-- Run in a transaction and ROLLBACK: test customers never enter production data.
do $$ declare svc uuid; cust uuid; ap uuid; r jsonb; t timestamptz; count_before int; begin
select id into svc from public.services limit 1;
t:=((current_date+3)::text||' 10:00 Europe/Brussels')::timestamptz;
update public.settings set value=value||jsonb_build_object('allowed_postcodes',jsonb_build_array('9300'),'lead_hours',0) where key='planning';
insert into public.availability(starts_at,ends_at,kind) values(t-interval '1 hour',t+interval '9 hours','open');
if not private.available(svc,t,'9300') then raise exception 'TEST availability'; end if;
if private.available(svc,t,'9999') then raise exception 'TEST area'; end if;
r:=private.luxwash_dispatch('book',jsonb_build_object('name','TEST transaction rollback','email','test@example.invalid','phone','+32000000000','service_id',svc,'starts_at',t,'postcode','9300','address','TEST','vehicle','TEST','source','website','idempotency_key','test-book-1','manage_token_hash','test-hash'));
ap:=(r->'appointment'->>'id')::uuid;cust:=(r->'appointment'->>'customer_id')::uuid;
if ap is null then raise exception 'TEST booking'; end if;
if private.available(svc,t,'9300') then raise exception 'TEST overlap'; end if;
begin perform private.luxwash_dispatch('book',jsonb_build_object('name','TEST transaction rollback','email','test@example.invalid','service_id',svc,'starts_at',t,'postcode','9300','address','TEST','source','phone','idempotency_key','test-book-2'));raise exception 'TEST duplicate accepted'; exception when exclusion_violation then null; end;
r:=private.luxwash_dispatch('book',jsonb_build_object('name','TEST transaction rollback','email','test@example.invalid','idempotency_key','test-book-1'));
if (r->>'replayed')::boolean is distinct from true then raise exception 'TEST replay'; end if;
begin perform private.luxwash_dispatch('appointment_change',jsonb_build_object('id',ap,'token_hash','wrong','status','cancelled'));raise exception 'TEST unauthorized'; exception when insufficient_privilege then null; end;
r:=private.luxwash_dispatch('appointment_change',jsonb_build_object('id',ap,'token_hash','test-hash','starts_at',t+interval '4 hours'));
if not private.available(svc,t,'9300') then raise exception 'TEST move'; end if;
r:=private.luxwash_dispatch('appointment_change',jsonb_build_object('id',ap,'admin',true,'status','confirmed'));
if (select count(*) from public.automation_jobs where appointment_id=ap and status='queued')<>2 then raise exception 'TEST reminder dedup'; end if;
r:=private.luxwash_dispatch('appointment_change',jsonb_build_object('id',ap,'admin',true,'status','completed'));
if not exists(select 1 from public.review_requests where appointment_id=ap) then raise exception 'TEST reviews'; end if;
if not exists(select 1 from public.repeat_booking_suggestions where appointment_id=ap) then raise exception 'TEST repeat'; end if;
r:=private.luxwash_dispatch('claim_jobs','{}');
if r is null then raise exception 'TEST jobs'; end if;
if (select count(*) from public.customers where id=cust)<>1 then raise exception 'TEST customer'; end if;
r:=private.luxwash_dispatch('call_start','{"provider_call_id":"test-call","phone":"+32000000000"}');
r:=private.luxwash_dispatch('tool_claim','{"provider_call_id":"test-call","tool_call_id":"test-tool","name":"getServices"}');
if (r->>'claimed')::boolean is distinct from true then raise exception 'TEST tool claim'; end if;
r:=private.luxwash_dispatch('tool_claim','{"provider_call_id":"test-call","tool_call_id":"test-tool","name":"getServices"}');
if (r->>'claimed')::boolean is distinct from false then raise exception 'TEST tool dedup'; end if;
r:=private.luxwash_dispatch('rate','{"key":"test-limit","limit":1,"seconds":60}');
r:=private.luxwash_dispatch('rate','{"key":"test-limit","limit":1,"seconds":60}');
if (r->>'allowed')::boolean is distinct from false then raise exception 'TEST rate'; end if;
begin perform public.luxwash_rpc('invalid','list','{"table":"customers"}'); raise exception 'TEST bad secret accepted'; exception when insufficient_privilege then null; end;
end $$;
set local role anon;
do $$ begin begin perform * from public.customers;raise exception 'TEST anon leak';exception when insufficient_privilege then null;end;end $$;
reset role;
set local role authenticated;
do $$ begin if (select count(*) from public.customers)<>0 then raise exception 'TEST authenticated leak';end if;end $$;
reset role;
select 'PASS: booking, identity reuse, conflict, move, capability auth, reminder, completion, review, repeat, jobs, call dedup, rate limit, RLS' as test_result;
