const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const querystring=require('querystring');
const config=require('./src/config');const makeStore=require('./src/store');const makeMessenger=require('./src/messaging');const makeAi=require('./src/ai');const makeAutomation=require('./src/automation');const html=require('./src/html');const {makeAdminCookie,verifyAdminCookie,parseCookies}=require('./src/auth');
const store=makeStore();const messenger=makeMessenger(config,store);const ai=makeAi(config);const automation=makeAutomation(config,store,messenger);const PUBLIC=path.join(__dirname,'public');const hits=new Map();
function headers(extra={}){return {'X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()',...extra}}
function send(res,status,body,type='text/html; charset=utf-8',extra={}){res.writeHead(status,headers({'Content-Type':type,...extra}));res.end(body)}
function json(res,status,obj,extra={}){send(res,status,JSON.stringify(obj),'application/json; charset=utf-8',extra)}
function redirect(res,to,extra={}){send(res,302,'','text/plain',{'Location':to,...extra})}
function safeEq(a,b){const A=Buffer.from(String(a)),B=Buffer.from(String(b));return A.length===B.length&&crypto.timingSafeEqual(A,B)}
function isAdmin(req){return verifyAdminCookie(parseCookies(req.headers.cookie||'').aba_admin,config.cookieSecret)}
function rateOk(req,key,limit,windowMs){const ip=req.socket.remoteAddress||'x';const k=key+ip;const now=Date.now();const a=(hits.get(k)||[]).filter(t=>now-t<windowMs);if(a.length>=limit)return false;a.push(now);hits.set(k,a);return true}
async function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>100000){reject(new Error('te groot'));req.destroy()}});req.on('end',()=>{const ct=req.headers['content-type']||'';try{if(ct.includes('application/json'))resolve(d?JSON.parse(d):{});else if(ct.includes('application/x-www-form-urlencoded'))resolve(querystring.parse(d));else resolve({raw:d})}catch(e){reject(e)}});req.on('error',reject)})}
function staticFile(url,res){const map={'/app.css':'app.css','/public.js':'public.js','/admin.js':'admin.js'};if(!map[url])return false;const f=path.join(PUBLIC,map[url]);const type=url.endsWith('.css')?'text/css; charset=utf-8':'application/javascript; charset=utf-8';send(res,200,fs.readFileSync(f),type,{'Cache-Control':'public, max-age=3600'});return true}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,config.baseUrl);const p=u.pathname;if(staticFile(p,res))return;
 if(req.method==='GET'&&p==='/health')return json(res,200,{ok:true,service:'ai-business-automation'});
 if(req.method==='GET'&&p==='/')return send(res,200,html.publicHome(config.business));
 if(req.method==='POST'&&p==='/api/leads'){if(!rateOk(req,'lead',30,60000))return json(res,429,{error:'Te veel aanvragen'});const b=await body(req);const {name,email,phone,service,message}=b;if(!name||(!email&&!phone))return json(res,400,{error:'Naam en e-mail of telefoon zijn verplicht.'});const follow=new Date(Date.now()+config.leadFollowupHours*36e5).toISOString();const lead=await store.createLead({name:String(name).slice(0,120),email:String(email||'').slice(0,160),phone:String(phone||'').slice(0,60),service:String(service||'').slice(0,160),message:String(message||'').slice(0,1500),source:'website',follow_up_at:follow,next_action:`Automatische follow-up binnen ${config.leadFollowupHours}u`});const text=`Dag ${lead.name}, bedankt voor je aanvraag bij ${config.business.name}. We hebben je vraag goed ontvangen${lead.service?` over ${lead.service}`:''} en nemen contact met je op.`;await messenger.sendBest({lead,subject:`Aanvraag ontvangen — ${config.business.name}`,text,type:'lead_confirmation'});return json(res,201,{ok:true,id:lead.id});}
 if(req.method==='POST'&&p==='/api/chat'){if(!rateOk(req,'chat',30,60000))return json(res,429,{error:'Te veel berichten'});const b=await body(req);const message=String(b.message||'').trim().slice(0,2000);if(!message)return json(res,400,{error:'Bericht ontbreekt'});try{const out=await ai.answer(message);return json(res,200,{answer:out.text,mode:out.mode})}catch(e){console.error(e);return json(res,500,{answer:'Ik kan je vraag nu niet verwerken. Laat je contactgegevens achter via het formulier.'})}}
 if(req.method==='GET'&&p==='/admin/login'){if(isAdmin(req))return redirect(res,'/admin');return send(res,200,html.loginPage(config.business));}
 if(req.method==='POST'&&p==='/admin/login'){if(!rateOk(req,'login',10,15*60000))return send(res,429,'Te veel pogingen');const b=await body(req);if(!safeEq(b.password||'',config.adminPassword))return send(res,401,html.loginPage(config.business,'Onjuist wachtwoord.'));const token=makeAdminCookie(config.cookieSecret);return redirect(res,'/admin',{'Set-Cookie':`aba_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`});}
 if(req.method==='POST'&&p==='/admin/logout')return json(res,200,{ok:true},{'Set-Cookie':'aba_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'});
 if(p.startsWith('/admin')&&!isAdmin(req))return redirect(res,'/admin/login');
 if(p.startsWith('/api/admin/')&&!isAdmin(req))return json(res,401,{error:'Niet ingelogd'});
 if(req.method==='GET'&&p==='/admin'){const [leads,appts,events]=await Promise.all([store.listLeads(),store.listAppointments(),store.listEvents(500)]);const now=Date.now();return send(res,200,html.dashboard(config.business,{total:leads.length,newLeads:leads.filter(x=>x.status==='new').length,upcoming:appts.filter(a=>a.status==='scheduled'&&new Date(a.starts_at).getTime()>now).length,sent:events.filter(e=>['sent','demo'].includes(e.status)).length,ai:Boolean(config.openaiKey),smtp:messenger.emailReady,whatsapp:Boolean(config.whatsapp.token&&config.whatsapp.phoneNumberId),db:false}));}
 if(req.method==='GET'&&p==='/admin/leads')return send(res,200,html.leadsPage(config.business,await store.listLeads()));
 if(req.method==='GET'&&p==='/admin/appointments'){const [a,l]=await Promise.all([store.listAppointments(),store.listLeads()]);return send(res,200,html.appointmentsPage(config.business,a,l));}
 if(req.method==='GET'&&p==='/admin/activity')return send(res,200,html.activityPage(config.business,await store.listEvents(200)));
 const mLead=p.match(/^\/api\/admin\/leads\/([a-f0-9-]+)$/);if(req.method==='PATCH'&&mLead){const b=await body(req);const allowed=['status','next_action','follow_up_at','last_contact_at'];const patch=Object.fromEntries(Object.entries(b).filter(([k])=>allowed.includes(k)));const row=await store.updateLead(mLead[1],patch);return row?json(res,200,row):json(res,404,{error:'Lead niet gevonden'})}
 if(req.method==='POST'&&p==='/api/admin/appointments'){const b=await body(req);if(!b.lead_id||!b.starts_at)return json(res,400,{error:'Klant en datum/tijd zijn verplicht'});const lead=await store.getLead(b.lead_id);if(!lead)return json(res,404,{error:'Lead niet gevonden'});const row=await store.createAppointment({lead_id:b.lead_id,starts_at:new Date(b.starts_at).toISOString(),status:'scheduled'});await store.updateLead(b.lead_id,{status:'won',next_action:'Afspraak gepland'});return json(res,201,row)}
 const mAppt=p.match(/^\/api\/admin\/appointments\/([a-f0-9-]+)$/);if(req.method==='PATCH'&&mAppt){const b=await body(req);const allowed=['status','reminder_sent_at','completed_at'];const patch=Object.fromEntries(Object.entries(b).filter(([k])=>allowed.includes(k)));const row=await store.updateAppointment(mAppt[1],patch);return row?json(res,200,row):json(res,404,{error:'Afspraak niet gevonden'})}
 if(req.method==='POST'&&p==='/api/admin/automation/run')return json(res,200,await automation.run());
 if(req.method==='POST'&&p==='/api/cron/run'){const supplied=req.headers['x-cron-secret']||u.searchParams.get('secret')||'';if(!safeEq(supplied,config.cronSecret))return json(res,401,{error:'Ongeldige cron secret'});return json(res,200,await automation.run())}
 return send(res,404,'Niet gevonden','text/plain; charset=utf-8');
 }catch(e){console.error(e);return json(res,500,{error:'Interne serverfout'})}});
(async()=>{await store.init();server.listen(config.port,'0.0.0.0',()=>console.log(`AI Business Automation draait op ${config.baseUrl}`));})();
