import {createClient} from "https://esm.sh/@supabase/supabase-js@2.95.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-supabase-api-version","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors}); if(req.method!=="POST")return json({error:"Method"},405);
 try{
  const b=await req.json(), token=String(b.widget_token||""), message=String(b.message||"").trim().slice(0,2000); if(!token||!message)return json({error:"Ongeldige aanvraag"},400);
  const url=Deno.env.get("SUPABASE_URL")!, sec=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; const db=createClient(url,sec,{auth:{persistSession:false}});
  const {data:p}=await db.from("business_profiles").select("*").eq("widget_token",token).eq("widget_enabled",true).single(); if(!p)return json({error:"Widget niet gevonden"},404); const {data:o}=await db.from("organizations").select("plan,trial_ends_at,subscription_status,status").eq("id",p.organization_id).single(); if(!o||o.status==="suspended"||(o.plan==="trial"&&new Date(o.trial_ends_at)<new Date())||(["starter","pro","business"].includes(o.plan)&&!["active","trialing"].includes(o.subscription_status)))return json({error:"Deze receptionist is momenteel niet actief."},402);
  const ip=req.headers.get("cf-connecting-ip")||"unknown"; const enc=new TextEncoder().encode(token+":"+ip); const dig=await crypto.subtle.digest("SHA-256",enc); const hash=Array.from(new Uint8Array(dig)).map(x=>x.toString(16).padStart(2,"0")).join("");
  const since=new Date(Date.now()-60000).toISOString(); const {count}=await db.from("widget_rate_limits").select("id",{count:"exact",head:true}).eq("organization_id",p.organization_id).eq("client_hash",hash).gte("created_at",since); if((count||0)>=12)return json({error:"Even te veel berichten. Probeer over een minuut opnieuw."},429); await db.from("widget_rate_limits").insert({organization_id:p.organization_id,client_hash:hash});
  let leadId=b.lead_id||null, convId=b.conversation_id||null; if(!leadId){const {data:l,error}=await db.from("leads").insert({organization_id:p.organization_id,name:String(b.name||"Websitebezoeker").slice(0,120),email:b.email||null,source:"public_widget",status:"qualifying",score:20,summary:message,dedupe_key:"widget:"+crypto.randomUUID()}).select("id").single();if(error)throw error;leadId=l.id}
  if(!convId){const {data:c,error}=await db.from("conversations").insert({organization_id:p.organization_id,lead_id:leadId,channel:"web_chat",status:"open"}).select("id").single();if(error)throw error;convId=c.id}
  await db.from("messages").insert({organization_id:p.organization_id,conversation_id:convId,role:"customer",content:message}); await db.from("leads").update({last_contact_at:new Date().toISOString(),updated_at:new Date().toISOString(),summary:message}).eq("id",leadId).eq("organization_id",p.organization_id);
  const {data:hist}=await db.from("messages").select("role,content").eq("conversation_id",convId).order("created_at",{ascending:false}).limit(10); const history=(hist||[]).reverse().map((m:any)=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));
  const services=Array.isArray(p.services)?p.services:[]; const instructions=["Je bent "+(p.receptionist_name||"Ava")+", AI-receptionist van "+p.business_name+".","Antwoord vriendelijk, compact en professioneel in de taal van de klant.","Gebruik uitsluitend de gegeven bedrijfsinformatie. Verzin niets.","Een aanvraag is nooit automatisch een bevestigde afspraak.","Vraag maximaal één nuttige vervolgvraag tegelijk.","Beschrijving: "+(p.description||"niet ingevuld"),"Diensten: "+(services.join(", ")||"niet ingevuld"),"Openingsuren: "+JSON.stringify(p.opening_hours||{}),"Kwalificatievragen: "+JSON.stringify(p.qualification_questions||[]),"Escalatieregels: "+JSON.stringify(p.escalation_rules||[])].join("\n");
  const low=message.toLowerCase(); const human=/medewerker|mens|persoon|bellen|bel mij|contacteer/i.test(low); const appointment=/afspraak|boeken|inplannen|beschikbaar|reserv/i.test(low); const urgent=/dringend|spoed|urgent|klacht/i.test(low); if(human||urgent){await db.from("handoffs").insert({organization_id:p.organization_id,lead_id:leadId,conversation_id:convId,reason:urgent?"Urgente of gevoelige aanvraag":"Bezoeker vraagt menselijke opvolging",status:"open"});await db.from("leads").update({status:"handoff",score:urgent?90:80,updated_at:new Date().toISOString()}).eq("id",leadId)}else if(appointment){await db.from("tasks").insert({organization_id:p.organization_id,lead_id:leadId,title:"Afspraakaanvraag opvolgen",status:"open",priority:"high"});await db.from("leads").update({status:"qualified",score:70,updated_at:new Date().toISOString()}).eq("id",leadId)} let reply=""; const key=Deno.env.get("GEMINI_API_KEY"); if(key){const ai=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",{method:"POST",headers:{"x-goog-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({system_instruction:{parts:[{text:instructions}]},contents:history,generationConfig:{maxOutputTokens:700,temperature:.35,thinkingConfig:{thinkingBudget:0}}})});if(ai.ok){const j=await ai.json();reply=String(j?.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||"").join("")||"").trim();console.log("PUBLIC_AI gemini success")}}
  if(human||urgent) reply=urgent?"Ik geef dit meteen door voor persoonlijke opvolging. Laat eventueel uw telefoonnummer achter zodat een medewerker u kan bereiken.":"Natuurlijk. Ik geef dit door aan een medewerker voor persoonlijke opvolging. Laat eventueel uw telefoonnummer achter zodat we u kunnen bereiken."; else if(appointment) reply="Graag. Ik kan hier geen live beschikbaarheid bevestigen. Welke dag of periode past voor u het best? Een medewerker bevestigt daarna de afspraak."; else if(reply.length<25)reply="Bedankt voor uw bericht. Ik registreer uw aanvraag. Kunt u kort aangeven waarmee we u kunnen helpen?";
  await db.from("messages").insert({organization_id:p.organization_id,conversation_id:convId,role:"assistant",content:reply}); return json({reply,lead_id:leadId,conversation_id:convId,receptionist_name:p.receptionist_name||"Ava",business_name:p.business_name,lead_state:human||urgent?"handoff":appointment?"qualified":"qualifying"});
 }catch(e){console.error(e);return json({error:"De receptionist is tijdelijk niet beschikbaar."},500)}
});