const {z}=require('zod');
const uuid=z.string().uuid();
const phone=z.string().trim().max(25).transform(v=>{v=v.replace(/[\s().-]/g,'');if(v.startsWith('00'))v='+'+v.slice(2);if(v.startsWith('0'))v='+32'+v.slice(1);return v;}).refine(v=>/^\+[1-9][0-9]{7,14}$/.test(v),'Vul een geldig telefoonnummer in');
const contact=z.object({name:z.string().trim().min(2).max(120),email:z.union([z.string().email().max(160),z.literal('')]).optional(),phone:phone.optional(),marketing_consent:z.boolean().optional()}).refine(v=>v.email||v.phone,'E-mail of telefoon is verplicht');
const booking=z.object({name:z.string().trim().min(2).max(120),email:z.union([z.string().email().max(160),z.literal('')]).optional(),phone:phone.optional(),marketing_consent:z.boolean().optional(),service_id:uuid,category:z.string().max(80).default('standard'),starts_at:z.string().datetime({offset:true}),postcode:z.string().regex(/^\d{4}$/),address:z.string().trim().min(5).max(300),vehicle:z.string().max(160).default(''),notes:z.string().max(1500).default(''),confirmed_by_customer:z.literal(true),idempotency_key:z.string().min(16).max(120)}).refine(v=>v.email||v.phone,'E-mail of telefoon is verplicht');
const planning=z.object({all_postcodes:z.boolean().optional(),open_24_7:z.boolean().optional(),max_per_day:z.number().int().min(1).max(20),lead_hours:z.number().int().min(0).max(168),horizon_days:z.number().int().min(1).max(365),allowed_postcodes:z.array(z.string().regex(/^\d{4}$/)).max(500),opening_hours:z.array(z.object({weekday:z.number().int().min(1).max(7),start:z.string().regex(/^\d{2}:\d{2}$/),end:z.string().regex(/^\d{2}:\d{2}$/)}).refine(v=>v.start<v.end,'Sluiting moet na opening vallen')).max(21),reminder_hours:z.number().int().min(1).max(168),repeat_weeks:z.number().int().min(1).max(52)}).strict();
function safeEqual(a,b){const A=Buffer.from(String(a||'')),B=Buffer.from(String(b||''));return A.length>0&&A.length===B.length&&require('node:crypto').timingSafeEqual(A,B);}
const quoteSlot=z.object({quote_id:uuid,service_id:uuid,duration_minutes:z.number().int().min(15).max(1440),postcode:z.string().regex(/^[1-9]\d{3}$/),from:z.string().datetime({offset:true}),to:z.string().datetime({offset:true})}).refine(v=>Date.parse(v.to)>=Date.parse(v.from),'Einddatum moet na begindatum liggen');
const quoteBooking=z.object({quote_id:uuid,service_id:uuid,duration_minutes:z.number().int().min(15).max(1440),postcode:z.string().regex(/^[1-9]\d{3}$/),starts_at:z.string().datetime({offset:true}),address:z.string().trim().min(5).max(300),vehicle:z.string().max(160).default(''),notes:z.string().max(1500).default(''),idempotency_key:z.string().min(16).max(120),confirmed_by_customer:z.literal(true)});
module.exports={z,uuid,phone,contact,booking,planning,safeEqual,quoteSlot,quoteBooking};
