import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import QRCode from 'https://esm.sh/qrcode@1.5.4';

const SB='https://nahwlhptgdkwhjcfkhkt.supabase.co';
const KEY='sb_publishable_x_9D7Hrrq5R5OYJfnxKsUg_buzI2PPR';
const API=SB+'/functions/v1/tafelgo-api';
const PUB=SB+'/functions/v1/tafelgo-public';
const SITE=location.origin;
const supabase=createClient(SB,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const root=document.getElementById('root');
let boot=null, cart={}, customerCtx=null, activeTab='dashboard', pollTimer=null, channel=null;
const $=id=>document.getElementById(id);
const value=id=>$(id)?.value??'';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const euro=c=>'€'+((Number(c)||0)/100).toFixed(2).replace('.',',');
const dt=s=>new Date(s).toLocaleTimeString('nl-BE',{hour:'2-digit',minute:'2-digit'});
const nav=()=>`<div class="nav"><div class="wrap"><div class="brand">Tafel<b>&Go</b></div><div class="navBtns"><button class="btn secondary" onclick="location.href='${SITE}'">Info</button><button class="btn" onclick="location.href='${SITE}?app=1'">Restaurant login</button></div></div></div>`;
function toast(s){const e=$('toast');e.textContent=s;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2600)}
async function api(payload){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Niet aangemeld');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+session.access_token},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Actie mislukt');return j;}

function landing(){root.innerHTML=nav()+`<section class="hero"><div class="wrap heroGrid"><div><span class="eyebrow">QR-BESTELLEN VOOR HORECA</span><h1>Meer bestellingen. Minder wachten.</h1><p>Gasten scannen de QR-code op tafel, bekijken je menu en sturen hun bestelling rechtstreeks naar je live keukenbord.</p><div class="pillrow" style="margin-top:24px"><button class="btn" onclick="location.href='${SITE}?app=1&signup=1'">Start 7 dagen gratis</button><button class="btn secondary" onclick="document.getElementById('werking').scrollIntoView()">Bekijk hoe het werkt</button></div></div><div class="heroCard"><div class="muted">Tafel&Go abonnement</div><div><span class="price">€29</span> / maand</div><p class="ok">✓ 7 dagen proefperiode</p><p>✓ QR-code per tafel<br>✓ Digitaal menu & winkelmand<br>✓ Live keukenbord<br>✓ Ober & rekening oproepen<br>✓ Restaurantdashboard</p><button class="btn" style="width:100%" onclick="location.href='${SITE}?app=1&signup=1'">Restaurant toevoegen</button></div></div></section><section class="section" id="werking"><div class="wrap"><h2>Van QR tot keuken in seconden</h2><p class="muted">Geen app nodig voor gasten.</p><div class="grid3" style="margin-top:22px"><div class="card feature"><div class="icon">▦</div><h3>1. Gast scant</h3><p class="muted">Elke tafel krijgt een unieke QR-code die direct het juiste restaurant en tafelnummer opent.</p></div><div class="card feature"><div class="icon">🛒</div><h3>2. Gast bestelt</h3><p class="muted">Menu bekijken, producten toevoegen en de bestelling versturen vanaf de eigen smartphone.</p></div><div class="card feature"><div class="icon">👨‍🍳</div><h3>3. Keuken ziet het live</h3><p class="muted">Nieuwe orders verschijnen op het keukenbord en gaan van nieuw naar bezig, klaar en geserveerd.</p></div></div></div></section><section class="section" style="background:#fff"><div class="wrap"><h2>Gebouwd voor echte service</h2><div class="grid3" style="margin-top:20px"><div class="card"><b>Menu zelf beheren</b><p class="muted">Categorieën, prijzen, uitverkocht-status en zichtbaarheid pas je zelf aan.</p></div><div class="card"><b>Ober oproepen</b><p class="muted">Gasten kunnen hulp of de rekening vragen. De oproep verschijnt live in je restaurantdashboard.</p></div><div class="card"><b>Live overzicht</b><p class="muted">Orders van vandaag, orderwaarde, gemiddelde bestelling en openstaande orders centraal zichtbaar.</p></div></div></div></section><footer class="foot"><div class="wrap"><b>Tafel&Go</b><div>QR-bestellen voor restaurants, cafés en horeca.</div></div></footer>`;}

function authScreen(signup=false){root.innerHTML=nav()+`<div class="appShell"><div class="wrap"><div class="card authBox"><h2>${signup?'Restaurant starten':'Welkom terug'}</h2><p class="muted">${signup?'Maak je account aan en stel daarna je echte restaurant en tafels in.':'Log in om je restaurant te beheren.'}</p><div class="authToggle"><button class="btn ${signup?'secondary':''}" onclick="showAuth(false)">Inloggen</button><button class="btn ${signup?'':'secondary'}" onclick="showAuth(true)">Account maken</button></div><form class="form" onsubmit="authSubmit(event,${signup})"><div class="field"><label>E-mail</label><input id="authEmail" type="email" required autocomplete="email"></div><div class="field"><label>Wachtwoord</label><input id="authPass" type="password" minlength="8" required autocomplete="${signup?'new-password':'current-password'}"></div><button class="btn" type="submit">${signup?'Account maken':'Inloggen'}</button><div id="authMsg"></div></form></div></div></div>`;}
window.showAuth=authScreen;
window.authSubmit=async(e,signup)=>{e.preventDefault();const email=value('authEmail').trim(),password=value('authPass'),msg=$('authMsg');msg.innerHTML='';const options={emailRedirectTo:SITE+'?app=1'};const {data,error}=signup?await supabase.auth.signUp({email,password,options}):await supabase.auth.signInWithPassword({email,password});if(error){msg.innerHTML='<div class="error">'+esc(error.message)+'</div>';return}if(signup&&!data.session){msg.innerHTML='<div class="success">Account gemaakt. Controleer je e-mail om je account te bevestigen.</div>';return}location.href=SITE+'?app=1';};
window.logout=async()=>{await supabase.auth.signOut();location.href=SITE};

async function loadApp(){const {data:{session}}=await supabase.auth.getSession();if(!session){authScreen(new URLSearchParams(location.search).get('signup')==='1');return}try{boot=await api({action:'bootstrap'});if(!boot.has_restaurant){onboard();return}renderApp();subscribeRealtime();}catch(e){root.innerHTML=nav()+`<div class="wrap"><div class="error" style="margin-top:30px">${esc(e.message)}</div></div>`}}
function onboard(){root.innerHTML=nav()+`<div class="appShell"><div class="wrap"><div class="card authBox"><h2>Stel je restaurant in</h2><p class="muted">Hiermee worden je echte tafels en QR-codes gemaakt. Er worden geen fictieve menu-items toegevoegd.</p><form class="form" onsubmit="onboardSubmit(event)"><div class="field"><label>Restaurantnaam</label><input id="obName" required placeholder="Bijv. Brasserie Central"></div><div class="field"><label>URL-naam</label><input id="obSlug" required placeholder="brasserie-central" pattern="[a-z0-9-]{3,50}"></div><div class="field"><label>Aantal tafels</label><input id="obTables" type="number" min="1" max="100" value="10" required></div><button class="btn">Restaurant aanmaken</button><div class="notice">Na de setup activeer je de 7-daagse proefperiode via Stripe. Tot dan kun je je restaurant voorbereiden.</div></form></div></div></div>`;}
window.onboardSubmit=async e=>{e.preventDefault();try{await api({action:'onboard',name:value('obName'),slug:value('obSlug'),table_count:Number(value('obTables'))});toast('Restaurant aangemaakt');await loadApp()}catch(x){toast(x.message)}};
function statusText(r){if(r.subscription_status==='active')return'Actief';if(r.subscription_status==='trialing')return'Proefperiode';if(r.subscription_status==='past_due')return'Betaling nodig';if(r.subscription_status==='cancelled')return'Beëindigd';return'Proefperiode nog activeren';}
function appHeader(){const t=boot.tables[0];const sample=t?`${SITE}?r=${encodeURIComponent(boot.restaurant.slug)}&t=${encodeURIComponent(t.public_token)}`:SITE;return `<div class="nav"><div class="wrap"><div class="brand">Tafel<b>&Go</b></div><div class="navBtns"><button class="btn secondary" onclick="location.href='${sample}'">Voorbeeld menu</button><button class="btn" onclick="logout()">Uitloggen</button></div></div></div>`;}
function renderApp(){root.innerHTML=appHeader()+`<div class="appShell"><div class="wrap"><div class="appTop"><div><h2 style="margin:0">${esc(boot.restaurant.name)}</h2><div class="muted">${esc(statusText(boot.restaurant))} · ${esc(boot.role)}</div></div><span class="badge ${['active','trialing'].includes(boot.restaurant.subscription_status)?'ready':'preparing'}">${esc(statusText(boot.restaurant))}</span></div><div class="tabs">${[['dashboard','Overzicht'],['kitchen','Keuken'],['menu','Menu'],['tables','Tafels & QR'],['settings','Instellingen'],['billing','Abonnement']].map(x=>`<button class="tab ${activeTab===x[0]?'active':''}" onclick="setTab('${x[0]}')">${x[1]}</button>`).join('')}</div><div id="view"></div></div></div>`;renderTab();}
window.setTab=t=>{activeTab=t;renderApp()};
function renderTab(){const v=$('view');if(!v)return;if(activeTab==='dashboard')dashboard(v);else if(activeTab==='kitchen')kitchen(v);else if(activeTab==='menu')menuAdmin(v);else if(activeTab==='tables')tables(v);else if(activeTab==='settings')settings(v);else billing(v);}
function orderCard(o){return `<div class="order"><div class="orderHead"><div><b>${esc(o.table?.label||('Tafel '+(o.table?.table_number||'')))}</b><div class="muted">${dt(o.created_at)} · ${euro(o.total_cents)}</div></div><span class="badge ${o.status}">${esc(o.status)}</span></div><div style="margin-top:8px">${(o.items||[]).map(i=>`${i.quantity}× ${esc(i.name_snapshot)}`).join('<br>')}</div>${o.note?`<div class="muted" style="margin-top:6px">Opmerking: ${esc(o.note)}</div>`:''}</div>`;}
function callCard(c){const t=boot.tables.find(x=>x.id===c.table_id);return `<div class="order call"><b>${esc(t?.label||'Tafel')}</b><div>${c.call_type==='bill'?'Rekening gevraagd':'Ober gevraagd'}</div><div class="muted">${dt(c.created_at)}</div><button class="btn small" style="margin-top:8px" onclick="handleCall('${c.id}')">Afgehandeld</button></div>`;}
function dashboard(v){const m=boot.metrics;v.innerHTML=`<div class="stats"><div class="stat"><span class="muted">Orders vandaag</span><strong>${m.orders_today}</strong></div><div class="stat"><span class="muted">Orderwaarde</span><strong>${euro(m.revenue_today_cents)}</strong></div><div class="stat"><span class="muted">Gem. order</span><strong>${euro(m.average_order_cents)}</strong></div><div class="stat"><span class="muted">Open orders</span><strong>${m.open_orders}</strong></div><div class="stat"><span class="muted">Oproepen</span><strong>${m.open_calls}</strong></div></div><div class="two"><div class="card"><h3>Laatste bestellingen</h3><div class="list">${boot.orders.slice(0,15).map(orderCard).join('')||'<div class="empty">Nog geen bestellingen.</div>'}</div></div><div class="card"><h3>Ober & rekening</h3><div class="list">${boot.calls.filter(c=>c.status==='open').map(callCard).join('')||'<div class="empty">Geen open oproepen.</div>'}</div></div></div>`;}
window.handleCall=async id=>{try{await api({action:'call_handle',id});await refresh(false)}catch(e){toast(e.message)}};
function kitchen(v){const active=boot.orders.filter(o=>!['served','cancelled'].includes(o.status));v.innerHTML=`<div class="card" style="margin-bottom:14px"><div class="orderHead"><div><h3 style="margin:0">Live keukenbord</h3><div class="muted">Nieuwe bestellingen verschijnen automatisch.</div></div><button class="btn secondary small" onclick="refresh(false)">Vernieuwen</button></div></div><div class="kitchen">${active.map(o=>`<div class="order"><div class="orderHead"><div><b style="font-size:20px">${esc(o.table?.label||'Tafel')}</b><div class="muted">${dt(o.created_at)} · ${euro(o.total_cents)}</div></div><span class="badge ${o.status}">${esc(o.status)}</span></div><div style="font-size:17px;margin:12px 0">${(o.items||[]).map(i=>`<b>${i.quantity}×</b> ${esc(i.name_snapshot)}`).join('<br>')}</div>${o.note?`<div class="notice">${esc(o.note)}</div>`:''}<div class="pillrow"><button class="btn small secondary" onclick="setOrder('${o.id}','accepted')">Aannemen</button><button class="btn small dark" onclick="setOrder('${o.id}','preparing')">Bezig</button><button class="btn small" onclick="setOrder('${o.id}','ready')">Klaar</button><button class="btn small secondary" onclick="setOrder('${o.id}','served')">Geserveerd</button></div></div>`).join('')||'<div class="card empty">Geen open bestellingen.</div>'}</div><div class="card" style="margin-top:16px"><h3>Open oproepen</h3><div class="grid3">${boot.calls.filter(c=>c.status==='open').map(callCard).join('')||'<div class="empty">Geen open oproepen.</div>'}</div></div>`;}
window.setOrder=async(id,status)=>{try{await api({action:'order_status',id,status});await refresh(false)}catch(e){toast(e.message)}};
function menuAdmin(v){v.innerHTML=`<div class="two"><div><div class="card"><div class="orderHead"><div><h3 style="margin:0">Categorieën</h3><div class="muted">Groepeer je menukaart.</div></div><button class="btn small" onclick="addCategory()">+ Categorie</button></div><div class="list" style="margin-top:12px">${boot.categories.map(c=>`<div class="order"><b>${esc(c.name)}</b><button class="btn small danger" style="float:right" onclick="deleteCategory('${c.id}')">Verwijder</button></div>`).join('')||'<div class="empty">Nog geen categorieën.</div>'}</div></div><div class="card" style="margin-top:14px"><h3>Nieuw menu-item</h3><form class="form" onsubmit="addItem(event)"><div class="field"><label>Categorie</label><select id="miCat"><option value="">Geen categorie</option>${boot.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Naam</label><input id="miName" required></div><div class="field"><label>Omschrijving</label><textarea id="miDesc" rows="2"></textarea></div><div class="field"><label>Prijs (€)</label><input id="miPrice" type="number" min="0" step="0.01" required></div><button class="btn">Item toevoegen</button></form></div></div><div class="card"><h3>Menukaart</h3><div class="list">${boot.items.map(i=>`<div class="menuItem ${i.sold_out?'sold':''}"><div class="orderHead"><div><b>${esc(i.name)}</b><div class="muted">${euro(i.price_cents)}</div></div><span class="badge">${i.sold_out?'Uitverkocht':'Beschikbaar'}</span></div><p class="muted">${esc(i.description)}</p><div class="pillrow"><button class="btn small secondary" onclick="editItem('${i.id}')">Bewerk</button><button class="btn small dark" onclick="toggleSold('${i.id}',${!i.sold_out})">${i.sold_out?'Terug beschikbaar':'Uitverkocht'}</button><button class="btn small danger" onclick="deleteItem('${i.id}')">Verwijder</button></div></div>`).join('')||'<div class="empty">Voeg je eerste echte menu-item toe.</div>'}</div></div></div>`;}
window.addCategory=async()=>{const name=prompt('Naam van de categorie');if(!name)return;try{await api({action:'category_upsert',name});await refresh(false)}catch(e){toast(e.message)}};
window.deleteCategory=async id=>{if(!confirm('Categorie verwijderen? Menu-items blijven bestaan zonder categorie.'))return;try{await api({action:'category_delete',id});await refresh(false)}catch(e){toast(e.message)}};
window.addItem=async e=>{e.preventDefault();try{await api({action:'item_upsert',category_id:value('miCat')||null,name:value('miName'),description:value('miDesc'),price_cents:Math.round(Number(value('miPrice'))*100)});toast('Menu-item toegevoegd');await refresh(false)}catch(x){toast(x.message)}};
window.toggleSold=async(id,sold_out)=>{try{await api({action:'item_toggle',id,sold_out});await refresh(false)}catch(e){toast(e.message)}};
window.deleteItem=async id=>{if(!confirm('Menu-item verwijderen?'))return;try{await api({action:'item_delete',id});await refresh(false)}catch(e){toast(e.message)}};
window.editItem=async id=>{const i=boot.items.find(x=>x.id===id);if(!i)return;const name=prompt('Naam',i.name);if(!name)return;const price=prompt('Prijs in euro',String(i.price_cents/100));if(price===null)return;const desc=prompt('Omschrijving',i.description||'');try{await api({action:'item_upsert',id,name,description:desc??i.description,price_cents:Math.round(Number(price)*100),category_id:i.category_id,sold_out:i.sold_out,active:i.active,sort_order:i.sort_order});await refresh(false)}catch(e){toast(e.message)}};
function tables(v){v.innerHTML=`<div class="card"><div class="orderHead"><div><h3 style="margin:0">Tafels & QR-codes</h3><div class="muted">Print de QR-code per tafel. Elke code bevat een unieke, niet-radenbare tafeltoken.</div></div><button class="btn" onclick="addTable()">+ Tafel</button></div></div><div class="tables" style="margin-top:14px">${boot.tables.map(t=>{const url=SITE+'?r='+encodeURIComponent(boot.restaurant.slug)+'&t='+encodeURIComponent(t.public_token);return `<div class="tableCard"><h3>${esc(t.label||('Tafel '+t.table_number))}</h3><img id="qr-${t.id}" alt="QR ${esc(t.label||t.table_number)}"><div class="muted" style="font-size:12px;word-break:break-all">${esc(url)}</div><div class="pillrow" style="justify-content:center;margin-top:10px"><button class="btn small" onclick="downloadQr('${t.id}','${esc(t.label||('Tafel '+t.table_number)).replace(/'/g,'&#39;')}')">Download QR</button><button class="btn small secondary" onclick="location.href='${url}'">Open</button><button class="btn small ${t.active?'danger':'secondary'}" onclick="toggleTable('${t.id}',${!t.active})">${t.active?'Pauzeer':'Activeer'}</button></div></div>`}).join('')}</div>`;setTimeout(generateQrs,0);}
async function generateQrs(){for(const t of boot.tables){const url=SITE+'?r='+encodeURIComponent(boot.restaurant.slug)+'&t='+encodeURIComponent(t.public_token);try{const data=await QRCode.toDataURL(url,{width:420,margin:2,errorCorrectionLevel:'M'});const img=$('qr-'+t.id);if(img)img.src=data}catch{}}}
window.downloadQr=(id,label)=>{const img=$('qr-'+id);if(!img?.src)return;const a=document.createElement('a');a.href=img.src;a.download=('TafelGo-'+label).replace(/[^a-z0-9_-]+/gi,'-')+'.png';a.click()};
window.addTable=async()=>{try{await api({action:'table_create'});await refresh(false)}catch(e){toast(e.message)}};
window.toggleTable=async(id,active)=>{try{await api({action:'table_set',id,active});await refresh(false)}catch(e){toast(e.message)}};
function settings(v){v.innerHTML=`<div class="card" style="max-width:680px"><h3>Restaurantinstellingen</h3><form class="form" onsubmit="saveSettings(event)"><div class="field"><label>Restaurantnaam</label><input id="setName" value="${esc(boot.restaurant.name)}" required></div><div class="field"><label>Accentkleur</label><input id="setColor" type="color" value="${esc(boot.restaurant.primary_color)}"></div><label style="display:flex;gap:9px;align-items:center"><input id="setOrdering" type="checkbox" ${boot.restaurant.ordering_enabled?'checked':''}> Bestellingen via QR toestaan</label><button class="btn">Opslaan</button></form></div>`;}
window.saveSettings=async e=>{e.preventDefault();try{await api({action:'settings',name:value('setName'),primary_color:value('setColor'),ordering_enabled:$('setOrdering').checked});toast('Opgeslagen');await refresh(false)}catch(x){toast(x.message)}};
function billing(v){const u=boot.stripe?.url||'';v.innerHTML=`<div class="card" style="max-width:720px"><h3>Tafel&Go abonnement</h3><div><span class="price">€29</span> / maand</div><p><b>Status:</b> ${esc(statusText(boot.restaurant))}</p><p class="muted">7 dagen proefperiode. Daarna maandelijks opzegbaar.</p>${u?`<button class="btn" onclick="startCheckout()">${boot.restaurant.subscription_status==='pending_payment'?'Start 7 dagen proefperiode':'Open Stripe checkout'}</button>`:'<div class="notice">Stripe-checkout wordt gekoppeld.</div>'}<p class="muted" style="margin-top:14px">De gekoppelde Stripe-account staat momenteel in testmodus. Er wordt nog geen echt geld geïnd.</p></div>`;}
window.startCheckout=()=>{let u=boot.stripe?.url||'';if(!u)return;u+=(u.includes('?')?'&':'?')+'client_reference_id='+encodeURIComponent(boot.restaurant.id);if(boot.user?.email)u+='&prefilled_email='+encodeURIComponent(boot.user.email);location.href=u};
async function refresh(redraw=true){try{boot=await api({action:'bootstrap'});if(redraw)renderApp();else renderTab()}catch(e){toast(e.message)}}window.refresh=refresh;
function subscribeRealtime(){if(channel)supabase.removeChannel(channel);if(!boot?.restaurant?.id)return;channel=supabase.channel('tg-'+boot.restaurant.id).on('postgres_changes',{event:'*',schema:'public',table:'tg_orders',filter:'restaurant_id=eq.'+boot.restaurant.id},()=>refresh(false)).on('postgres_changes',{event:'*',schema:'public',table:'tg_staff_calls',filter:'restaurant_id=eq.'+boot.restaurant.id},()=>refresh(false)).subscribe();}

async function customerMode(r,t){root.innerHTML='<div class="customerBody"><div class="customerMain"><div class="card">Menu laden…</div></div></div>';try{const res=await fetch(PUB+'?r='+encodeURIComponent(r)+'&t='+encodeURIComponent(t));const j=await res.json();if(!res.ok)throw new Error(j.error||'Menu niet beschikbaar');customerCtx=j;renderCustomer()}catch(e){root.innerHTML=`<div class="customerBody"><div class="customerMain"><div class="error">Dit menu is niet beschikbaar. ${esc(e.message)}</div></div></div>`}}
function renderCustomer(){const j=customerCtx,brand=/^#[0-9a-f]{6}$/i.test(j.restaurant.primary_color||'')?j.restaurant.primary_color:'#0f172a';root.innerHTML=`<div class="customerBody"><div class="customerHead" style="background:${brand}"><div class="inner"><div><b style="font-size:21px">${esc(j.restaurant.name)}</b><div style="opacity:.8">${esc(j.table.label||('Tafel '+j.table.table_number))}</div></div><div class="pillrow"><button class="btn small secondary" onclick="staffCall('waiter')">Ober</button><button class="btn small secondary" onclick="staffCall('bill')">Rekening</button></div></div></div><main class="customerMain"><div class="chips"><button class="chip" onclick="filterCat('')">Alles</button>${j.categories.map(c=>`<button class="chip" onclick="filterCat('${c.id}')">${esc(c.name)}</button>`).join('')}</div><div id="foods">${foodHtml('')}</div></main><div class="cartBar"><div class="inner"><div><b id="cartCount">0 items</b><div id="cartTotal" class="muted">€0,00</div></div><button class="btn" onclick="openCart()">Bekijk bestelling</button></div></div></div><div id="modal"></div>`;updateCartBar();}
function foodHtml(cat){return customerCtx.items.filter(i=>!cat||i.category_id===cat).map(i=>`<div class="food ${i.sold_out?'sold':''}"><div><h3>${esc(i.name)}</h3><p>${esc(i.description)}</p><div class="p">${euro(i.price_cents)}</div></div><div>${i.sold_out?'<span class="badge">Uitverkocht</span>':`<button class="btn small" onclick="addCart('${i.id}')">+ Voeg toe</button>`}</div></div>`).join('')||'<div class="empty">Geen items in deze categorie.</div>'}
window.filterCat=id=>{const f=$('foods');if(f)f.innerHTML=foodHtml(id)};
window.addCart=id=>{cart[id]=(cart[id]||0)+1;updateCartBar();toast('Toegevoegd')};
function cartTotals(){let n=0,total=0;for(const [id,q] of Object.entries(cart)){const i=customerCtx.items.find(x=>x.id===id);if(i){n+=q;total+=i.price_cents*q}}return{n,total}}
function updateCartBar(){const x=cartTotals(),a=$('cartCount'),b=$('cartTotal');if(a)a.textContent=x.n+' '+(x.n===1?'item':'items');if(b)b.textContent=euro(x.total)}
window.changeQty=(id,d)=>{cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];openCart();updateCartBar()};
window.openCart=()=>{const m=$('modal'),x=cartTotals();m.innerHTML=`<div class="modal"><div class="modalBox"><div class="modalHead"><h2>Je bestelling</h2><button class="btn small secondary" onclick="closeModal()">✕</button></div>${Object.entries(cart).map(([id,q])=>{const i=customerCtx.items.find(x=>x.id===id);return i?`<div class="cartLine"><div><b>${esc(i.name)}</b><div class="muted">${euro(i.price_cents)}</div></div><div class="qty"><button onclick="changeQty('${id}',-1)">−</button><b>${q}</b><button onclick="changeQty('${id}',1)">+</button></div></div>`:''}).join('')||'<div class="empty">Je winkelmand is leeg.</div>'}<div style="display:flex;justify-content:space-between;font-size:20px;padding:14px 0"><b>Totaal</b><b>${euro(x.total)}</b></div>${x.n?`<form class="form" onsubmit="placeOrder(event)"><div class="field"><label>Naam (optioneel)</label><input id="custName" maxlength="80"></div><div class="field"><label>Opmerking (optioneel)</label><textarea id="custNote" maxlength="500" rows="2" placeholder="Bijv. zonder ijs"></textarea></div><div class="notice">Betaling gebeurt bij het restaurant. Online tafelbetalingen zijn nog niet ingeschakeld.</div><button class="btn" style="width:100%">Bestelling versturen</button></form>`:''}</div></div>`};
window.closeModal=()=>{const m=$('modal');if(m)m.innerHTML=''};
window.placeOrder=async e=>{e.preventDefault();const sp=new URLSearchParams(location.search),items=Object.entries(cart).map(([item_id,quantity])=>({item_id,quantity}));const r=await fetch(PUB,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'order',restaurant_slug:sp.get('r'),table_token:sp.get('t'),items,customer_name:value('custName'),note:value('custNote'),payment_method:'at_counter'})});const j=await r.json().catch(()=>({}));if(!r.ok){toast(j.error||'Bestelling mislukt');return}cart={};closeModal();updateCartBar();trackOrder(j.order.token)};
window.staffCall=async type=>{const sp=new URLSearchParams(location.search),r=await fetch(PUB,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'call',restaurant_slug:sp.get('r'),table_token:sp.get('t'),call_type:type})});const j=await r.json().catch(()=>({}));toast(r.ok?(type==='bill'?'Rekening gevraagd':'Ober is verwittigd'):(j.error||'Niet gelukt'))};
async function trackOrder(token){if(pollTimer)clearInterval(pollTimer);const show=async()=>{const r=await fetch(PUB+'?order='+encodeURIComponent(token)),j=await r.json().catch(()=>({}));if(!r.ok)return;const labels={new:'Ontvangen',accepted:'Aangenomen',preparing:'In bereiding',ready:'Klaar',served:'Geserveerd',cancelled:'Geannuleerd'},m=$('modal');if(!m)return;m.innerHTML=`<div class="modal"><div class="modalBox"><h2>Bestelling ${esc(labels[j.order.status]||j.order.status)}</h2><p class="muted">Totaal: ${euro(j.order.total_cents)}</p><div class="notice">Je bestelling is doorgestuurd. Deze status wordt automatisch bijgewerkt.</div>${j.items.map(i=>`<div class="cartLine"><span>${i.quantity}× ${esc(i.name_snapshot)}</span><b>${euro(i.price_cents_snapshot*i.quantity)}</b></div>`).join('')}<button class="btn secondary" style="width:100%;margin-top:14px" onclick="closeModal()">Sluiten</button></div></div>`;if(['served','cancelled'].includes(j.order.status))clearInterval(pollTimer)};await show();pollTimer=setInterval(show,7000)}

const sp=new URLSearchParams(location.search),r=sp.get('r'),t=sp.get('t');
if(r&&t)customerMode(r,t);else if(sp.get('app')==='1')loadApp();else landing();
