function esc(s='') { return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

function shell(title, body, business, admin=false) {
  return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><link rel="stylesheet" href="/app.css"></head><body>
  <header class="top"><a class="brand" href="${admin?'/admin':'/'}"><span class="logo">AI</span><span>${esc(business.name)}</span></a>${admin?'<nav><a href="/admin">Dashboard</a><a href="/admin/leads">Leads</a><a href="/admin/appointments">Afspraken</a><a href="/admin/activity">Activiteit</a><button id="logoutBtn" class="linkbtn">Uitloggen</button></nav>':''}</header>
  <main>${body}</main><footer>AI Business Automatisering · ${esc(business.name)}</footer>${admin?'<script src="/admin.js"></script>':''}</body></html>`;
}

function publicHome(b) {
  const options=b.services.map(x=>`<option>${esc(x)}</option>`).join('');
  return shell(b.name, `<section class="hero"><div><span class="eyebrow">Slimme service, sneller antwoord</span><h1>${esc(b.name)}</h1><p>Vraag informatie, een prijsindicatie of een afspraak aan. Onze digitale assistent helpt je meteen.</p><div class="chips"><span>${esc(b.area)}</span><span>${esc(b.hours)}</span></div></div><div class="card"><h2>Vraag contact aan</h2><form id="leadForm"><label>Naam<input name="name" required></label><label>E-mail<input name="email" type="email"></label><label>Telefoon<input name="phone"></label><label>Dienst<select name="service"><option value="">Kies een dienst</option>${options}</select></label><label>Vraag<textarea name="message" rows="4"></textarea></label><button type="submit">Verstuur aanvraag</button><p id="leadStatus" class="status"></p></form></div></section><section class="assistant"><div class="chathead"><strong>AI klantenassistent</strong><span>● online</span></div><div id="chatLog" class="chatlog"><div class="bubble bot">Hallo! Waarmee kan ik je helpen?</div></div><form id="chatForm" class="chatinput"><input id="chatInput" placeholder="Vraag naar prijs, uren, regio…" autocomplete="off"><button>Stuur</button></form></section><script src="/public.js"></script>`, b);
}

function loginPage(b,error='') { return shell('Beheerlogin', `<section class="login"><div class="card"><h1>Beheer</h1><p>Log in op de automatiseringsomgeving.</p>${error?`<p class="error">${esc(error)}</p>`:''}<form method="post" action="/admin/login"><label>Wachtwoord<input type="password" name="password" required autofocus></label><button type="submit">Inloggen</button></form></div></section>`,b); }

function dashboard(b, stats) { return shell('Dashboard', `<section class="adminwrap"><div class="adminhead"><div><span class="eyebrow">Automatisering</span><h1>Dashboard</h1><p>${esc(b.name)}</p></div><button data-action="run-automation">Automatiseringen nu uitvoeren</button></div><div class="statgrid"><div class="stat"><b>${stats.total}</b><span>Leads totaal</span></div><div class="stat"><b>${stats.newLeads}</b><span>Nieuwe leads</span></div><div class="stat"><b>${stats.upcoming}</b><span>Komende afspraken</span></div><div class="stat"><b>${stats.sent}</b><span>Verzonden acties</span></div></div><div class="grid2"><div class="card"><h2>Workflow</h2><ol class="flow"><li>Nieuwe aanvraag registreren</li><li>Bevestiging naar klant</li><li>Automatische follow-up</li><li>Afspraak + herinnering</li><li>Reviewverzoek na uitvoering</li></ol></div><div class="card"><h2>Integratiestatus</h2><p><span class="dot ${stats.ai?'ok':'demo'}"></span> AI: ${stats.ai?'live':'demo/fallback'}</p><p><span class="dot ${stats.smtp?'ok':'demo'}"></span> E-mail: ${stats.smtp?'live':'demo-log'}</p><p><span class="dot ${stats.whatsapp?'ok':'demo'}"></span> WhatsApp: ${stats.whatsapp?'live':'demo-log'}</p><p><span class="dot ${stats.db?'ok':'demo'}"></span> Database: ${stats.db?'PostgreSQL':'lokale demo-opslag'}</p></div></div></section>`, b, true); }

function leadsPage(b, leads) { return shell('Leads', `<section class="adminwrap"><div class="adminhead"><div><span class="eyebrow">CRM</span><h1>Leads</h1></div></div><div class="tablewrap"><table><thead><tr><th>Naam</th><th>Dienst</th><th>Contact</th><th>Status</th><th>Volgende actie</th><th>Aangemaakt</th></tr></thead><tbody>${leads.map(l=>`<tr><td><b>${esc(l.name)}</b><br><small>${esc(l.message||'')}</small></td><td>${esc(l.service||'-')}</td><td>${esc(l.email||l.phone||'-')}</td><td><select class="status-select" data-lead="${l.id}">${['new','contacted','quoted','won','lost'].map(s=>`<option value="${s}" ${l.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${esc(l.next_action||'-')}</td><td>${new Date(l.created_at).toLocaleString('nl-BE')}</td></tr>`).join('')||'<tr><td colspan="6">Nog geen leads.</td></tr>'}</tbody></table></div></section>`,b,true); }

function appointmentsPage(b, appts, leads) { const leadMap=Object.fromEntries(leads.map(l=>[l.id,l])); return shell('Afspraken', `<section class="adminwrap"><div class="adminhead"><div><span class="eyebrow">Planning</span><h1>Afspraken</h1></div></div><div class="grid2"><div class="card"><h2>Nieuwe afspraak</h2><form id="appointmentForm"><label>Klant<select name="lead_id" required><option value="">Kies lead</option>${leads.map(l=>`<option value="${l.id}">${esc(l.name)} — ${esc(l.service||'')}</option>`).join('')}</select></label><label>Datum & tijd<input name="starts_at" type="datetime-local" required></label><button>Afspraak opslaan</button><p id="appointmentStatus" class="status"></p></form></div><div class="card"><h2>Komende / recente afspraken</h2><div class="apptlist">${appts.map(a=>{const l=leadMap[a.lead_id]||{};return `<div class="appt"><div><b>${esc(l.name||'Onbekend')}</b><br><span>${new Date(a.starts_at).toLocaleString('nl-BE')}</span></div><select class="appt-status" data-appt="${a.id}">${['scheduled','completed','cancelled'].map(s=>`<option value="${s}" ${a.status===s?'selected':''}>${s}</option>`).join('')}</select></div>`}).join('')||'<p>Nog geen afspraken.</p>'}</div></div></div></section>`,b,true); }

function activityPage(b, events) { return shell('Activiteit', `<section class="adminwrap"><div class="adminhead"><div><span class="eyebrow">Logboek</span><h1>Automatiseringsactiviteit</h1></div></div><div class="tablewrap"><table><thead><tr><th>Tijd</th><th>Type</th><th>Kanaal</th><th>Status</th><th>Detail</th></tr></thead><tbody>${events.map(e=>`<tr><td>${new Date(e.created_at).toLocaleString('nl-BE')}</td><td>${esc(e.type)}</td><td>${esc(e.channel||'-')}</td><td>${esc(e.status||'-')}</td><td>${esc(e.detail||'')}</td></tr>`).join('')||'<tr><td colspan="5">Nog geen activiteit.</td></tr>'}</tbody></table></div></section>`,b,true); }

module.exports = { publicHome, loginPage, dashboard, leadsPage, appointmentsPage, activityPage };
