-- LuxWash appointment AI persistent conversation/state layer.
-- Operational service availability and bookings continue to use the existing LuxWash CRM/planning RPC.

create table if not exists public.appointment_agent_sessions (
  session_id text primary key,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointment_agent_messages (
  id bigint generated by default as identity primary key,
  session_id text not null references public.appointment_agent_sessions(session_id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);
create index if not exists appointment_agent_messages_session_idx
  on public.appointment_agent_messages(session_id, created_at desc);

create table if not exists public.appointment_agent_leads (
  id uuid primary key default gen_random_uuid(),
  email_key text unique not null,
  email text not null,
  full_name text not null default '',
  phone text not null default '',
  summary text not null default '',
  guide_sent_at timestamptz,
  followup_count integer not null default 0 check (followup_count between 0 and 10),
  next_followup_at timestamptz,
  followup_complete boolean not null default false,
  booked boolean not null default false,
  booking_start timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists appointment_agent_leads_followup_idx
  on public.appointment_agent_leads(next_followup_at)
  where followup_complete=false and booked=false;

create table if not exists public.appointment_agent_bookings (
  id uuid primary key default gen_random_uuid(),
  email_key text not null,
  email text not null,
  full_name text not null,
  phone text not null default '',
  starts_at timestamptz not null unique,
  ends_at timestamptz not null,
  timezone text not null default 'Europe/Brussels',
  status text not null default 'booked' check (status in ('booked','cancelled','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(email_key, starts_at)
);

create index if not exists appointment_agent_bookings_range_idx
  on public.appointment_agent_bookings(starts_at, ends_at);

alter table public.appointment_agent_sessions enable row level security;
alter table public.appointment_agent_messages enable row level security;
alter table public.appointment_agent_leads enable row level security;
alter table public.appointment_agent_bookings enable row level security;

revoke all on public.appointment_agent_sessions from anon, authenticated;
revoke all on public.appointment_agent_messages from anon, authenticated;
revoke all on public.appointment_agent_leads from anon, authenticated;
revoke all on public.appointment_agent_bookings from anon, authenticated;

create or replace function public.appointment_agent_rpc(
  p_secret text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path to 'public','extensions'
as $$
declare
  v_email text;
  v_session text;
  v_start timestamptz;
  v_end timestamptz;
  v_row jsonb;
  v_out jsonb;
begin
  -- Reuse the production app-secret validation already owned by ai_business_rpc.
  perform public.ai_business_rpc(p_secret,'health','{}'::jsonb);

  case p_action
    when 'health' then
      return jsonb_build_object('ok',true);

    when 'session_get' then
      v_session := left(coalesce(p_payload->>'session_id',''),160);
      if v_session='' then raise exception 'session_id_required'; end if;
      insert into public.appointment_agent_sessions(session_id) values(v_session)
      on conflict(session_id) do update set updated_at=now();
      select jsonb_build_object(
        'session_id', s.session_id,
        'state', s.state,
        'history', coalesce((
          select jsonb_agg(jsonb_build_object(
            'role',q.role,'content',q.content,'created_at',q.created_at
          ) order by q.created_at asc)
          from (
            select role,content,created_at
            from public.appointment_agent_messages
            where session_id=v_session
            order by created_at desc
            limit 20
          ) q
        ),'[]'::jsonb)
      ) into v_out
      from public.appointment_agent_sessions s
      where s.session_id=v_session;
      return v_out;

    when 'session_state' then
      v_session := left(coalesce(p_payload->>'session_id',''),160);
      if v_session='' then raise exception 'session_id_required'; end if;
      insert into public.appointment_agent_sessions(session_id,state,updated_at)
      values(v_session,coalesce(p_payload->'state','{}'::jsonb),now())
      on conflict(session_id) do update set state=excluded.state,updated_at=now();
      return '{"ok":true}'::jsonb;

    when 'message_add' then
      v_session := left(coalesce(p_payload->>'session_id',''),160);
      if v_session='' then raise exception 'session_id_required'; end if;
      if (p_payload->>'role') not in ('user','assistant') then raise exception 'invalid_role'; end if;
      insert into public.appointment_agent_sessions(session_id) values(v_session)
      on conflict(session_id) do update set updated_at=now();
      insert into public.appointment_agent_messages(session_id,role,content)
      values(v_session,p_payload->>'role',left(coalesce(p_payload->>'content',''),4000));
      return '{"ok":true}'::jsonb;

    when 'lead_upsert' then
      v_email := lower(trim(coalesce(p_payload->>'email','')));
      if v_email='' then raise exception 'email_required'; end if;
      insert into public.appointment_agent_leads(
        email_key,email,full_name,phone,summary,updated_at
      ) values(
        v_email,v_email,left(coalesce(p_payload->>'full_name',''),160),
        left(coalesce(p_payload->>'phone',''),80),
        left(coalesce(p_payload->>'summary',''),2000),now()
      )
      on conflict(email_key) do update set
        full_name=case when excluded.full_name<>'' then excluded.full_name else appointment_agent_leads.full_name end,
        phone=case when excluded.phone<>'' then excluded.phone else appointment_agent_leads.phone end,
        summary=case when excluded.summary<>'' then excluded.summary else appointment_agent_leads.summary end,
        updated_at=now()
      returning to_jsonb(appointment_agent_leads.*) into v_row;
      return v_row;

    when 'lead_get' then
      v_email := lower(trim(coalesce(p_payload->>'email','')));
      select to_jsonb(l.*) into v_row
      from public.appointment_agent_leads l
      where email_key=v_email;
      return coalesce(v_row,'null'::jsonb);

    when 'guide_mark' then
      v_email := lower(trim(coalesce(p_payload->>'email','')));
      update public.appointment_agent_leads set
        guide_sent_at=coalesce(guide_sent_at,now()),
        next_followup_at=case when guide_sent_at is null then now()+interval '24 hours' else next_followup_at end,
        followup_complete=false,
        updated_at=now()
      where email_key=v_email
      returning to_jsonb(appointment_agent_leads.*) into v_row;
      return coalesce(v_row,'null'::jsonb);

    when 'followup_due' then
      select coalesce(jsonb_agg(to_jsonb(x) order by x.next_followup_at asc),'[]'::jsonb)
      into v_out
      from (
        select * from public.appointment_agent_leads
        where guide_sent_at is not null
          and booked=false
          and followup_complete=false
          and next_followup_at is not null
          and next_followup_at<=now()
        order by next_followup_at asc
        limit greatest(1,least(coalesce((p_payload->>'limit')::int,20),100))
      ) x;
      return v_out;

    when 'followup_mark' then
      v_email := lower(trim(coalesce(p_payload->>'email','')));
      update public.appointment_agent_leads set
        followup_count=greatest(0,least(coalesce((p_payload->>'followup_count')::int,followup_count),10)),
        next_followup_at=nullif(p_payload->>'next_followup_at','')::timestamptz,
        followup_complete=coalesce((p_payload->>'followup_complete')::boolean,followup_complete),
        updated_at=now()
      where email_key=v_email
      returning to_jsonb(appointment_agent_leads.*) into v_row;
      return coalesce(v_row,'null'::jsonb);

    when 'bookings_between' then
      v_start := (p_payload->>'from')::timestamptz;
      v_end := (p_payload->>'to')::timestamptz;
      select coalesce(jsonb_agg(jsonb_build_object(
        'id',id,'starts_at',starts_at,'ends_at',ends_at,'status',status
      ) order by starts_at),'[]'::jsonb)
      into v_out
      from public.appointment_agent_bookings
      where status='booked' and starts_at < v_end and ends_at > v_start;
      return v_out;

    when 'book' then
      v_email := lower(trim(coalesce(p_payload->>'email','')));
      v_start := (p_payload->>'starts_at')::timestamptz;
      v_end := (p_payload->>'ends_at')::timestamptz;
      if v_email='' then raise exception 'email_required'; end if;
      if v_start < now()+interval '1 hour' then raise exception 'slot_too_soon'; end if;
      if exists(
        select 1 from public.appointment_agent_bookings
        where status='booked' and starts_at < v_end and ends_at > v_start
      ) then raise exception 'slot_unavailable'; end if;
      insert into public.appointment_agent_bookings(
        email_key,email,full_name,phone,starts_at,ends_at,timezone,status
      ) values(
        v_email,v_email,left(coalesce(p_payload->>'full_name',''),160),
        left(coalesce(p_payload->>'phone',''),80),v_start,v_end,
        left(coalesce(p_payload->>'timezone','Europe/Brussels'),80),'booked'
      )
      on conflict(email_key,starts_at) do update set updated_at=now()
      returning to_jsonb(appointment_agent_bookings.*) into v_row;
      update public.appointment_agent_leads set
        booked=true,booking_start=v_start,followup_complete=true,next_followup_at=null,updated_at=now()
      where email_key=v_email;
      return v_row;

    when 'cleanup' then
      delete from public.appointment_agent_messages where created_at < now()-interval '30 days';
      delete from public.appointment_agent_sessions where updated_at < now()-interval '30 days';
      return '{"ok":true}'::jsonb;

    else
      raise exception 'unknown_action';
  end case;
end
$$;

revoke all on function public.appointment_agent_rpc(text,text,jsonb) from public;
grant execute on function public.appointment_agent_rpc(text,text,jsonb)
  to anon,authenticated,service_role;
