plugins {
    id 'com.android.application'
}

android {
    namespace 'online.luxwash.voice'
    compileSdk 35

    defaultConfig {
        applicationId "online.luxwash.voice.v12"
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName "1.2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
