import React,{useEffect,useState} from 'react';
type Row=Record<string,any>;
async function api(path:string,data?:any){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw new Error(value.error||'Gegevens ophalen mislukt');return value;}
const money=(n:any)=>new Intl.NumberFormat('nl-BE',{style:'currency',currency:'EUR'}).format(Number(n||0)/100);
const when=(v:any)=>v?new Date(v).toLocaleString('nl-BE',{timeZone:'Europe/Brussels',dateStyle:'medium',timeStyle:'short'}):'—';
export function FlowPanel({onNavigate,compact=false}:{onNavigate:(value:string)=>void,compact?:boolean}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;api('/api/core/admin/flow').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 if(error)return <div className="alert" role="alert">Bedrijfsflow kon niet worden geladen: {error}</div>;
 if(!data)return <section className="panel" role="status">Acties controleren…</section>;
 const actions=data.actions||[],sources=data.sources||[],total=sources.reduce((n:number,x:Row)=>n+Number(x.leads),0);
 return <><section className="panel flow-action-panel"><div className="panel-heading"><div><p className="eyebrow">CENTRALE KLANTFLOW</p><h2>Actie vereist <span className="flow-count">{actions.length}</span></h2></div><button className="secondary" onClick={()=>onNavigate('automations')}>Automatiseringen</button></div>{!actions.length?<p>Geen openstaande acties gevonden in het CRM.</p>:<div className="flow-action-list">{actions.slice(0,compact?4:30).map((item:Row)=><button className="flow-action" key={item.id} onClick={()=>onNavigate(item.target)}><span><strong>{item.title}</strong><small>{when(item.due_at)}</small></span><span>{item.priority==='high'?'Prioriteit':'Bekijken'} →</span></button>)}</div>}<p className="muted">Gecontroleerd: {when(data.checked_at)}. Cijfers zijn gebaseerd op opgeslagen gegevens.</p></section>
 {!compact&&<><section className="panel"><h2>Wat loopt automatisch?</h2><p className="muted">Laatste voltooide verwerkingsronde: {data.worker?when(data.worker.checked_at):'Nog niet geregistreerd'}</p><div className="flow-rule-grid"><article><strong>Nieuwe aanvraag</strong><p>Opslaan → klant herkennen → ontvangstmail in wachtrij → eigenaarstaak.</p></article><article><strong>Afspraak</strong><p>Beschikbaarheid → boeking → bevestiging → herinnering → opvolging.</p></article><article><strong>Offerte</strong><p>Concept → interne goedkeuring → beveiligde link → klantakkoord → inplannen.</p></article><article><strong>Antwoord of uitschrijving</strong><p>Opgeslagen antwoorden stoppen vervolgberichten. Uitschrijvingen blokkeren onderhoudsuitnodigingen.</p></article></div><div className="notice">Automatische leadvervolgmails zijn nog uitgeschakeld: eerst moet verwerking van inkomende antwoorden worden getest. Openstaande aanvragen verschijnen wel automatisch als taak.</div><p>De huidige gratis backendhosting kan pauzeren bij inactiviteit. Een continue 24/7-verwerking is daarmee niet gegarandeerd.</p><a className="button secondary" href="/api/core/admin/calendar.ics">Agenda downloaden (.ics)</a><p className="muted">Importeer de export in uw agenda. Dit is geen automatische Google Calendar-synchronisatie.</p></section>
 <div className="integration-grid">{(data.integrations||[]).map((item:Row)=><article className="panel" key={item.name}><h2>{item.name}</h2><span className={'flow-status '+(item.status==='LIVE'?'live':item.status==='FOUT'?'error':'pending')}>{item.status}</span><p>{item.detail}</p></article>)}</div>
 <section className="panel"><h2>Inzicht in aanvragen</h2>{total<5?<p>Er zijn nog te weinig opgeslagen aanvragen om betrouwbare groeitrends te bepalen.</p>:<p>{sources[0]?.source} leverde tot nu toe de meeste opgeslagen aanvragen ({sources[0]?.leads}). Vergelijk ook hoeveel daarvan tot een afspraak leidden.</p>}<div className="table-wrap"><table><thead><tr><th>Bron</th><th>Aanvragen</th><th>Gekoppelde afspraken</th></tr></thead><tbody>{sources.map((x:Row)=><tr key={x.source}><td>{x.source}</td><td>{x.leads}</td><td>{x.bookings}</td></tr>)}</tbody></table></div><p className="muted">Geen verzonnen bezoekers- of socialcijfers. Resultaten uit kanalen zonder gegevenskoppeling zijn niet inbegrepen.</p></section>
 <section className="panel"><h2>Klantwaarde</h2><div className="table-wrap"><table><thead><tr><th>Klant</th><th>Uitgevoerde afspraken</th><th>Geregistreerde netto betalingen</th></tr></thead><tbody>{(data.customers||[]).map((c:Row)=><tr key={c.id}><td>{c.name}</td><td>{c.completed_bookings}</td><td>{money(c.lifetime_value_cents)}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>Gebeurtenissen</h2><p className="muted">Nieuwe events sinds deze uitbreiding. Technische details bevatten geen berichtinhoud of contactgegevens.</p>{data.events?.length?<div className="table-wrap"><table><thead><tr><th>Moment</th><th>Gebeurtenis</th><th>Status</th></tr></thead><tbody>{data.events.map((event:Row)=><tr key={event.id}><td>{when(event.created_at)}</td><td>{event.type}</td><td>{event.status}</td></tr>)}</tbody></table></div>:<p>Nog geen nieuwe gebeurtenissen geregistreerd.</p>}</section></>}
 </>;
}
export function SocialPanel(){
 const [data,setData]=useState<Row[]>([]),[observation,setObservation]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({platform:'facebook',post_type:'post',caption:'',topic:'',media_prompt:''});
 async function refresh(){try{const [posts,flow]=await Promise.all([api('/api/core/admin/social'),api('/api/core/admin/flow')]);setData(posts.rows);setObservation(flow.metricool||null);}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/core/admin/social',form);setForm({...form,caption:'',topic:'',media_prompt:''});setNotice('Concept opgeslagen. Nog niet gepland of gepubliceerd.');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><section className="panel"><div className="panel-heading"><div><p className="eyebrow">BESTAANDE SOCIALKOPPELING</p><h2>Metricool</h2></div><a className="button" href="https://app.metricool.com/" target="_blank" rel="noopener noreferrer">Open Metricool ↗</a></div><p>Facebook · Instagram @luxwassh · TikTok @luxwash.lede · YouTube · Google Business Profile</p>{observation?<><span className={'flow-status '+(observation.publication_error?'error':'pending')}>{observation.publication_error?'FOUT BIJ PUBLICATIE':'ACCOUNT GECONTROLEERD'}</span><p>{observation.publication_error||'Kanalen zichtbaar in Metricool.'}</p><p className="muted">Account- en plannercontrole: {when(observation.checked_at)}. Dit is een momentopname, geen permanente verbindingsmeting.</p></>:<p>De accountstatus is nog niet in dit dashboard gecontroleerd.</p>}<p>De bestaande dagelijkse ChatGPT Social Agent gebruikt Metricool apart. Dit dashboard bewaart contentconcepten; een concept is niet automatisch gepubliceerd. WhatsApp hoort niet bij deze socialkoppeling.</p></section>
 {error&&<div className="alert" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <section className="panel"><h2>Contentconcept toevoegen</h2><form onSubmit={save}><div className="form-grid"><label>Kanaal<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{['facebook','instagram','tiktok','youtube','google_business'].map(x=><option key={x}>{x}</option>)}</select></label><label>Formaat<select value={form.post_type} onChange={e=>setForm({...form,post_type:e.target.value})}>{['post','reel','poll','short','story'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Onderwerp<input maxLength={200} value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}/></label><label>Tekst en CTA<textarea required maxLength={5000} rows={5} value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})}/></label><label>Beeld- of videoprompt (optioneel)<textarea maxLength={2000} value={form.media_prompt} onChange={e=>setForm({...form,media_prompt:e.target.value})}/></label><button disabled={busy}>Concept opslaan</button><p className="muted">Identieke teksten voor hetzelfde kanaal worden geweigerd. Controleer bij publicatie ook inhoudelijke herhaling en of alle claims en beelden echt zijn.</p></form></section>
 <section className="panel"><div className="panel-heading"><h2>Concepten en geïmporteerde plannerstatus</h2><button className="secondary" onClick={refresh}>Vernieuwen</button></div>{data.length?data.map(post=><article className="flow-social-post" key={post.id}><div className="panel-heading"><strong>{post.platform} · {post.post_type}</strong><span className={'flow-status '+(post.status==='failed'?'error':'pending')}>{({draft:'Concept',scheduled:'Gepland',failed:'Publicatiefout',published:'Gepubliceerd'} as Row)[post.status]||post.status}</span></div><p className="preserve-lines">{post.caption}</p>{post.last_error&&<p className="alert">{post.last_error}</p>}<small>{post.scheduled_at?'Gepland moment: '+when(post.scheduled_at):'Nog niet gepland'}{post.metadata?.checked_at?' · status gecontroleerd '+when(post.metadata.checked_at):''}</small></article>):<p>Nog geen content opgeslagen.</p>}</section></>;
}
export function QuotePage(){
 const [quote,setQuote]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[notice,setNotice]=useState('');
 const [id,token]=location.hash.slice(1).split('/');
 useEffect(()=>{if(!id||!token){setError('Open de persoonlijke offertelink uit de e-mail van LuxWash.');return;}api('/api/core/quote',{id,token}).then(setQuote).catch(e=>setError(e.message));},[]);
 async function decide(decision:string){setBusy(true);setError('');try{const result=await api('/api/core/quote',{id,token,decision,confirmed:true});setQuote(result);setNotice(decision==='accepted'?'Uw akkoord is opgeslagen. LuxWash neemt contact op om datum, duur en planning af te spreken. Er is nog geen tijdstip geboekt.':'Uw keuze is opgeslagen. Er worden geen automatische offertevervolgberichten verstuurd.');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="booking-page"><header className="booking-header"><a className="brand" href="https://www.luxwash.online"><img className="brand-mark" src="https://www.luxwash.online/brand/luxwash-logo-web.webp" alt="LuxWash"/><span>LUX<span className="blue">WASH</span></span></a><a href="tel:053896400">053 896 400</a></header><main className="booking-main"><p className="eyebrow">UW PERSOONLIJKE OFFERTE</p><h1>{quote?.title||'LuxWash-offerte'}</h1>{error&&<div className="alert" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}{quote&&<section className="panel quote-sheet"><div className="panel-heading"><div><h2>Voor {quote.customer?.name}</h2><p>Geldig tot {when(quote.expires_at)}</p></div><span className="badge">{({viewed:'Bekeken',approved:'Goedgekeurd door LuxWash',sent:'Verzonden',accepted:'Geaccepteerd',declined:'Geweigerd',expired:'Vervallen'} as Row)[quote.status]||quote.status}</span></div><p className="preserve-lines">{quote.notes}</p>{quote.items?.length>0&&<div className="table-wrap"><table><thead><tr><th>Omschrijving</th><th>Aantal</th><th>Prijs</th><th>Totaal</th></tr></thead><tbody>{quote.items.map((item:Row,i:number)=><tr key={i}><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unit_cents)}</td><td>{money(Math.round(Number(item.quantity)*item.unit_cents))}</td></tr>)}</tbody></table></div>}<p className="quote-total">Totaal <strong>{money(quote.total_cents)}</strong></p><p>Deze offerte bepaalt de werkzaamheden en prijs. Een afspraak wordt pas vastgelegd wanneer het tijdstip, de locatie en de duur zijn afgesproken en bevestigd.</p>{['viewed','approved','sent'].includes(quote.status)&&<div className="no-print"><label className="check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Ik heb de omschrijving en totaalprijs gelezen en ga akkoord met deze offerte.</label><div className="actions"><button disabled={busy||!confirmed} onClick={()=>decide('accepted')}>Offerte accepteren</button><button className="secondary" disabled={busy} onClick={()=>{if(window.confirm('Wilt u deze offerte weigeren?'))decide('declined')}}>Offerte weigeren</button></div></div>}<div className="actions no-print"><button className="secondary" onClick={()=>window.print()}>Afdrukken / opslaan als PDF</button><a href={'mailto:'+quote.business?.email}>Vraag stellen</a></div><footer>{quote.business?.name} · {quote.business?.phone} · {quote.business?.email}<br/>{quote.business?.website}</footer></section>}</main></div>;
}
