package com.bloombeyond.game;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.*;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public class GameView extends View {
    private static final int N=8,TYPES=6;
    private static final int HOME=0,SELECT=1,GAME=2,ESTATE=3,QUESTS=4,MINIGAME=5,REWARDS=6;
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), text=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final Random rng=new Random();
    private final SharedPreferences prefs;
    private final Vibrator vibrator;
    private final int[][] board=new int[N][N], power=new int[N][N], blocker=new int[N][N];
    private int mode=HOME,level=1,unlocked=1,score,moves,coins,stars,lives,wins,renovations;
    private int rockets,bombs,rainbows,selectedBooster=0,selR=-1,selC=-1,levelPage=0;
    private int dailyWins,dailyMatches,treasureScore,treasureTurns;
    private long lastLifeAt,lastDailyClaim;
    private boolean levelOver,won;
    private float boardLeft,boardTop,cell;
    private String banner=""; private long bannerUntil;
    private final int[] colors={Color.rgb(245,91,132),Color.rgb(255,184,70),Color.rgb(82,203,151),Color.rgb(80,157,243),Color.rgb(160,105,238),Color.rgb(239,108,205)};

    public GameView(Context c){
        super(c); setLayerType(View.LAYER_TYPE_SOFTWARE,null);
        prefs=c.getSharedPreferences("bloom_save",Context.MODE_PRIVATE);
        vibrator=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);
        unlocked=Math.max(1,Math.min(LevelCatalog.MAX_LEVEL,prefs.getInt("level",1)));
        level=unlocked; coins=prefs.getInt("coins",250); stars=prefs.getInt("stars",0); lives=prefs.getInt("lives",5);
        wins=prefs.getInt("wins",0); renovations=prefs.getInt("renovations",0); rockets=prefs.getInt("rocketBoosters",2); bombs=prefs.getInt("bombBoosters",1); rainbows=prefs.getInt("rainbowBoosters",1);
        dailyWins=prefs.getInt("dailyWins",0); dailyMatches=prefs.getInt("dailyMatches",0); lastLifeAt=prefs.getLong("lastLifeAt",System.currentTimeMillis()); lastDailyClaim=prefs.getLong("lastDailyClaim",0);
        text.setTypeface(Typeface.create("sans",Typeface.BOLD)); restoreLives(); newBoard();
    }

    private void restoreLives(){long now=System.currentTimeMillis(); if(lives<5){long gained=(now-lastLifeAt)/(20*60*1000L);if(gained>0){lives=Math.min(5,lives+(int)gained);lastLifeAt=now;save();}}else lastLifeAt=now;}
    private void startLevel(int l){restoreLives();if(lives<=0){show("No lives — one returns every 20 min");return;}level=Math.max(1,Math.min(unlocked,l));LevelCatalog.Spec s=LevelCatalog.get(level);score=0;moves=s.moves;levelOver=false;won=false;selR=selC=-1;newBoard();seedObstacles(s);mode=GAME;show(s.zone+" • "+s.goalLabel);invalidate();}
    private void newBoard(){for(int r=0;r<N;r++){Arrays.fill(power[r],0);Arrays.fill(blocker[r],0);}do{for(int r=0;r<N;r++)for(int c=0;c<N;c++){int v;do{v=rng.nextInt(TYPES);}while((c>=2&&board[r][c-1]==v&&board[r][c-2]==v)||(r>=2&&board[r-1][c]==v&&board[r-2][c]==v));board[r][c]=v;}}while(hasMatch());}
    private void seedObstacles(LevelCatalog.Spec s){int left=s.obstacleCount,guard=0;while(left>0&&guard++<500){int r=rng.nextInt(N),c=rng.nextInt(N);if(blocker[r][c]==0){int type=1+rng.nextInt(Math.max(1,s.maxObstacleType));int hp=(rng.nextInt(100)<s.hardTileChance)?2:1;blocker[r][c]=type*10+hp;left--;}}}

    @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();background(c,w,h);if(mode==HOME)home(c,w,h);else if(mode==SELECT)select(c,w,h);else if(mode==GAME)game(c,w,h);else if(mode==ESTATE)estate(c,w,h);else if(mode==QUESTS)quests(c,w,h);else if(mode==MINIGAME)mini(c,w,h);else rewards(c,w,h);if(System.currentTimeMillis()<bannerUntil)banner(c,w,h);}
    private void background(Canvas c,int w,int h){LinearGradient g=new LinearGradient(0,0,w,h,Color.rgb(27,43,73),Color.rgb(17,24,42),Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,w,h,p);p.setShader(null);for(int i=0;i<16;i++){p.setColor(Color.argb(16,255,255,255));c.drawCircle((i*97)%Math.max(1,w),(i*173)%Math.max(1,h),18+(i%5)*12,p);}}
    private void heading(Canvas c,int w,String sub){text.setTextAlign(Paint.Align.CENTER);text.setColor(Color.WHITE);text.setTextSize(dp(27));c.drawText("BLOOM & BEYOND",w/2f,dp(43),text);text.setTextSize(dp(11));text.setColor(Color.rgb(185,204,232));c.drawText(sub,w/2f,dp(65),text);}
    private void home(Canvas c,int w,int h){heading(c,w,"EVERBLOOM ESTATE • ADVENTURE");p.setColor(Color.rgb(45,79,67));c.drawRoundRect(dp(22),h*.14f,w-dp(22),h*.45f,dp(28),dp(28),p);p.setColor(Color.rgb(224,202,165));c.drawRect(w*.37f,h*.24f,w*.63f,h*.44f,p);p.setColor(Color.rgb(94,61,76));Path roof=new Path();roof.moveTo(w*.33f,h*.24f);roof.lineTo(w*.5f,h*.16f);roof.lineTo(w*.67f,h*.24f);roof.close();c.drawPath(roof,p);p.setColor(Color.rgb(91,151,102));c.drawCircle(w*.23f,h*.36f,dp(45),p);c.drawCircle(w*.77f,h*.35f,dp(55),p);text.setTextSize(dp(20));text.setColor(Color.WHITE);c.drawText("Restore a world full of secrets",w/2f,h*.51f,text);text.setTextSize(dp(12));text.setColor(Color.rgb(195,211,235));c.drawText("100 levels • 5 zones • quests • minigames",w/2f,h*.55f,text);button(c,w/2f,h*.63f,dp(245),dp(56),"PLAY LEVEL "+unlocked,true);button(c,w*.27f,h*.73f,dp(130),dp(46),"LEVELS",false);button(c,w*.73f,h*.73f,dp(130),dp(46),"ESTATE",false);button(c,w*.27f,h*.82f,dp(130),dp(46),"QUESTS",false);button(c,w*.73f,h*.82f,dp(130),dp(46),"TREASURE",false);text.setTextSize(dp(12));text.setColor(Color.rgb(176,198,225));c.drawText("❤ "+lives+"   🪙 "+coins+"   ★ "+stars+"   Wins "+wins,w/2f,h*.91f,text);}
    private void select(Canvas c,int w,int h){heading(c,w,"100-LEVEL CAMPAIGN");String zone=LevelCatalog.zoneFor(levelPage*20+1);text.setTextSize(dp(17));text.setColor(Color.WHITE);c.drawText(zone,w/2f,dp(103),text);int start=levelPage*20+1;float sx=w*.18f,sy=h*.20f,gx=w*.16f,gy=h*.105f;for(int i=0;i<20;i++){int lv=start+i,row=i/5,col=i%5;float x=sx+col*gx,y=sy+row*gy;boolean open=lv<=unlocked;p.setColor(open?(lv==unlocked?Color.rgb(247,188,72):Color.rgb(102,179,139)):Color.rgb(61,76,96));c.drawCircle(x,y,dp(25),p);text.setColor(open?Color.WHITE:Color.rgb(135,148,166));text.setTextSize(dp(12));c.drawText(String.valueOf(lv),x,y+dp(4),text);}button(c,w*.23f,h*.73f,dp(105),dp(42),"PREV",false);button(c,w*.50f,h*.73f,dp(105),dp(42),"HOME",false);button(c,w*.77f,h*.73f,dp(105),dp(42),"NEXT",false);text.setTextSize(dp(12));text.setColor(Color.rgb(176,198,225));c.drawText("Zone "+(levelPage+1)+"/5 • Unlocked "+unlocked+"/100",w/2f,h*.82f,text);}
    private void game(Canvas c,int w,int h){LevelCatalog.Spec s=LevelCatalog.get(level);heading(c,w,s.zone.toUpperCase());pill(c,w*.15f,dp(94),"LVL",level);pill(c,w*.39f,dp(94),"MOVES",moves);pill(c,w*.63f,dp(94),"GOAL",s.targetScore);pill(c,w*.87f,dp(94),"LEFT",obstacles());text.setTextSize(dp(12));text.setColor(Color.WHITE);c.drawText("Score "+score+" / "+s.targetScore,w/2f,dp(139),text);p.setColor(Color.argb(70,255,255,255));c.drawRoundRect(w*.12f,dp(149),w*.88f,dp(159),dp(7),dp(7),p);p.setColor(Color.rgb(102,217,164));c.drawRoundRect(w*.12f,dp(149),w*.12f+(w*.76f)*Math.min(1f,score/(float)s.targetScore),dp(159),dp(7),dp(7),p);cell=Math.min((w-dp(28))/N,(h*.53f)/N);boardLeft=(w-cell*N)/2;boardTop=h*.22f;p.setColor(Color.argb(105,5,12,25));c.drawRoundRect(boardLeft-dp(6),boardTop-dp(6),boardLeft+cell*N+dp(6),boardTop+cell*N+dp(6),dp(20),dp(20),p);for(int r=0;r<N;r++)for(int col=0;col<N;col++)gem(c,r,col);float fy=boardTop+cell*N+dp(31);text.setTextSize(dp(10));text.setColor(Color.rgb(194,211,235));c.drawText("Boosters: tap one, then tap a tile",w/2f,fy,text);booster(c,w*.26f,fy+dp(39),"ROCKET",rockets,1);booster(c,w*.50f,fy+dp(39),"BOMB",bombs,3);booster(c,w*.74f,fy+dp(39),"RAINBOW",rainbows,4);button(c,w*.28f,fy+dp(92),dp(120),dp(40),"LEVELS",false);button(c,w*.72f,fy+dp(92),dp(120),dp(40),"RESTART",false);if(levelOver)overlay(c,w,h);}
    private void pill(Canvas c,float x,float y,String lab,int val){p.setColor(Color.argb(170,13,25,45));c.drawRoundRect(x-dp(42),y-dp(23),x+dp(42),y+dp(23),dp(14),dp(14),p);text.setTextSize(dp(8));text.setColor(Color.rgb(154,179,210));c.drawText(lab,x,y-dp(4),text);text.setTextSize(dp(15));text.setColor(Color.WHITE);c.drawText(String.valueOf(val),x,y+dp(14),text);}
    private void gem(Canvas c,int r,int col){float cx=boardLeft+col*cell+cell/2,cy=boardTop+r*cell+cell/2,rad=cell*.35f;p.setColor(colors[board[r][col]]);p.setShadowLayer(dp(4),0,dp(2),Color.argb(100,0,0,0));c.drawCircle(cx,cy,rad,p);p.clearShadowLayer();p.setColor(Color.argb(95,255,255,255));c.drawCircle(cx-rad*.25f,cy-rad*.28f,rad*.16f,p);if(power[r][col]>0){text.setTextSize(dp(15));text.setColor(Color.WHITE);c.drawText(power[r][col]==1?"↔":power[r][col]==2?"↕":power[r][col]==3?"✹":"◎",cx,cy+dp(5),text);}if(blocker[r][col]>0){int type=blocker[r][col]/10,hp=blocker[r][col]%10;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(hp==2?5:3));p.setColor(obstacleColor(type));c.drawRoundRect(cx-rad*.95f,cy-rad*.95f,cx+rad*.95f,cy+rad*.95f,dp(7),dp(7),p);p.setStyle(Paint.Style.FILL);text.setTextSize(dp(8));text.setColor(Color.WHITE);c.drawText(obstacleSymbol(type),cx,cy+dp(3),text);}if(r==selR&&col==selC){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(4));p.setColor(Color.WHITE);c.drawCircle(cx,cy,rad*1.08f,p);p.setStyle(Paint.Style.FILL);}}
    private int obstacleColor(int t){return t==1?Color.rgb(174,117,73):t==2?Color.rgb(180,223,245):t==3?Color.rgb(80,150,88):t==4?Color.rgb(130,130,139):Color.rgb(224,178,69);}private String obstacleSymbol(int t){return t==1?"CR":t==2?"ICE":t==3?"VINE":t==4?"ROCK":"LOCK";}
    private void booster(Canvas c,float x,float y,String name,int count,int type){p.setColor(selectedBooster==type?Color.rgb(151,95,220):Color.rgb(47,68,102));c.drawRoundRect(x-dp(54),y-dp(25),x+dp(54),y+dp(25),dp(15),dp(15),p);text.setTextSize(dp(9));text.setColor(Color.WHITE);c.drawText(name+" x"+count,x,y+dp(4),text);}
    private void overlay(Canvas c,int w,int h){p.setColor(Color.argb(228,8,14,25));c.drawRect(0,0,w,h,p);p.setColor(Color.rgb(41,59,88));c.drawRoundRect(dp(30),h*.29f,w-dp(30),h*.70f,dp(28),dp(28),p);text.setTextSize(dp(28));text.setColor(Color.WHITE);c.drawText(won?"Level Complete!":"Out of moves",w/2f,h*.39f,text);text.setTextSize(dp(13));text.setColor(Color.rgb(200,216,238));c.drawText(won?"+1 star  •  +100 coins":"A life is used when you retry.",w/2f,h*.45f,text);button(c,w/2f,h*.56f,dp(220),dp(54),won?"NEXT LEVEL":"TRY AGAIN",true);button(c,w/2f,h*.64f,dp(170),dp(40),"LEVEL SELECT",false);}
    private void estate(Canvas c,int w,int h){heading(c,w,"ESTATE RESTORATION");p.setColor(Color.rgb(47,83,73));c.drawRoundRect(dp(25),h*.15f,w-dp(25),h*.52f,dp(26),dp(26),p);float prog=Math.min(1f,renovations/25f);p.setColor(Color.rgb(217,199,168));c.drawRect(w*.33f,h*.28f,w*.67f,h*.51f,p);p.setColor(Color.rgb(95,62,78));Path roof=new Path();roof.moveTo(w*.29f,h*.28f);roof.lineTo(w*.5f,h*.19f);roof.lineTo(w*.71f,h*.28f);roof.close();c.drawPath(roof,p);p.setColor(Color.rgb(86+(int)(60*prog),130+(int)(45*prog),92));c.drawCircle(w*.22f,h*.43f,dp(50),p);c.drawCircle(w*.78f,h*.42f,dp(55),p);text.setTextSize(dp(18));text.setColor(Color.WHITE);c.drawText("Estate progress "+renovations+" / 25",w/2f,h*.59f,text);text.setTextSize(dp(12));text.setColor(Color.rgb(190,209,233));c.drawText("Spend 1 star to restore the next feature",w/2f,h*.64f,text);button(c,w/2f,h*.72f,dp(230),dp(52),stars>0?"RESTORE • 1 STAR":"EARN A STAR",true);button(c,w/2f,h*.82f,dp(150),dp(42),"HOME",false);}
    private void quests(Canvas c,int w,int h){heading(c,w,"DAILY QUESTS & ACHIEVEMENTS");questCard(c,w,h*.20f,"Win 3 puzzle levels",dailyWins,3,150);questCard(c,w,h*.34f,"Create 25 matches",dailyMatches,25,1);questCard(c,w,h*.48f,"Restore 5 estate features",renovations,5,2);questCard(c,w,h*.62f,"Complete 20 levels",wins,20,3);button(c,w/2f,h*.82f,dp(150),dp(42),"HOME",false);}
    private void questCard(Canvas c,int w,float y,String label,int current,int goal,int rewardKind){p.setColor(Color.argb(175,31,50,80));c.drawRoundRect(dp(24),y-dp(45),w-dp(24),y+dp(45),dp(18),dp(18),p);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(dp(13));text.setColor(Color.WHITE);c.drawText(label,dp(42),y-dp(10),text);text.setTextSize(dp(11));text.setColor(Color.rgb(177,199,226));c.drawText(Math.min(current,goal)+" / "+goal,dp(42),y+dp(15),text);text.setTextAlign(Paint.Align.CENTER);p.setColor(current>=goal?Color.rgb(92,181,132):Color.rgb(75,93,122));c.drawRoundRect(w-dp(125),y-dp(22),w-dp(42),y+dp(22),dp(14),dp(14),p);text.setTextSize(dp(10));text.setColor(Color.WHITE);c.drawText(current>=goal?"CLAIM":"LOCKED",w-dp(83),y+dp(4),text);}
    private void mini(Canvas c,int w,int h){heading(c,w,"TREASURE GARDEN");text.setTextSize(dp(15));text.setColor(Color.WHITE);c.drawText("Pick a chest • 3 turns",w/2f,h*.14f,text);for(int i=0;i<6;i++){float x=w*(.22f+(i%3)*.28f),y=h*(.29f+(i/3)*.22f);p.setColor(Color.rgb(132,88,47));c.drawRoundRect(x-dp(43),y-dp(34),x+dp(43),y+dp(34),dp(12),dp(12),p);p.setColor(Color.rgb(239,188,67));c.drawRect(x-dp(43),y-dp(5),x+dp(43),y+dp(7),p);text.setTextSize(dp(11));text.setColor(Color.WHITE);c.drawText("CHEST "+(i+1),x,y+dp(30),text);}text.setTextSize(dp(14));text.setColor(Color.rgb(195,215,239));c.drawText("Treasure: "+treasureScore+" coins • Turns "+treasureTurns+"/3",w/2f,h*.73f,text);button(c,w/2f,h*.83f,dp(150),dp(42),"HOME",false);}
    private void rewards(Canvas c,int w,int h){heading(c,w,"DAILY REWARD");long day=System.currentTimeMillis()/(24*60*60*1000L),last=lastDailyClaim/(24*60*60*1000L);boolean ready=day>last;p.setColor(Color.rgb(50,74,109));c.drawRoundRect(dp(30),h*.22f,w-dp(30),h*.60f,dp(28),dp(28),p);text.setTextSize(dp(54));text.setColor(Color.rgb(246,195,73));c.drawText("★",w/2f,h*.38f,text);text.setTextSize(dp(20));text.setColor(Color.WHITE);c.drawText(ready?"Today's gift is ready!":"Come back tomorrow",w/2f,h*.47f,text);text.setTextSize(dp(13));text.setColor(Color.rgb(193,211,235));c.drawText("Reward: 200 coins + 1 rocket",w/2f,h*.52f,text);button(c,w/2f,h*.68f,dp(220),dp(52),ready?"CLAIM REWARD":"CLAIMED",ready);button(c,w/2f,h*.80f,dp(150),dp(42),"HOME",false);}
    private void button(Canvas c,float x,float y,float bw,float bh,String s,boolean primary){p.setColor(primary?Color.rgb(141,91,218):Color.rgb(48,69,104));c.drawRoundRect(x-bw/2,y-bh/2,x+bw/2,y+bh/2,dp(15),dp(15),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(dp(11));text.setColor(Color.WHITE);c.drawText(s,x,y+dp(4),text);}
    private void banner(Canvas c,int w,int h){p.setColor(Color.argb(235,12,23,41));c.drawRoundRect(dp(28),h*.115f,w-dp(28),h*.165f,dp(17),dp(17),p);text.setTextSize(dp(12));text.setColor(Color.WHITE);text.setTextAlign(Paint.Align.CENTER);c.drawText(banner,w/2f,h*.147f,text);postInvalidateDelayed(100);}

    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=e.getX(),y=e.getY();int w=getWidth(),h=getHeight();
        if(mode==HOME){if(y>h*.59f&&y<h*.68f)startLevel(unlocked);else if(y>h*.69f&&y<h*.77f){mode=x<w/2?SELECT:ESTATE;invalidate();}else if(y>h*.78f&&y<h*.87f){mode=x<w/2?QUESTS:MINIGAME;treasureTurns=0;treasureScore=0;invalidate();}else if(y>h*.88f){mode=REWARDS;invalidate();}return true;}
        if(mode==SELECT){if(y>h*.16f&&y<h*.63f){int col=Math.max(0,Math.min(4,(int)((x-w*.10f)/(w*.16f))));int row=Math.max(0,Math.min(3,(int)((y-h*.15f)/(h*.105f))));int lv=levelPage*20+row*5+col+1;if(lv<=unlocked)startLevel(lv);}else if(y>h*.69f&&y<h*.78f){if(x<w*.36f)levelPage=Math.max(0,levelPage-1);else if(x>w*.64f)levelPage=Math.min(4,levelPage+1);else mode=HOME;invalidate();}return true;}
        if(mode==ESTATE){if(y>h*.68f&&y<h*.77f){if(stars>0&&renovations<25){stars--;renovations++;coins+=25;show("Feature restored! +25 coins");save();}else if(stars<=0)show("Complete a level to earn stars");invalidate();}else if(y>h*.78f){mode=HOME;invalidate();}return true;}
        if(mode==QUESTS){if(y>h*.78f){mode=HOME;invalidate();}else claimQuest(y,h);return true;}
        if(mode==MINIGAME){if(y>h*.20f&&y<h*.60f&&treasureTurns<3){int gain=25+rng.nextInt(76);treasureScore+=gain;treasureTurns++;vibrate(25);show("Treasure +"+gain+" coins");if(treasureTurns==3){coins+=treasureScore;save();}}else if(y>h*.78f){mode=HOME;invalidate();}return true;}
        if(mode==REWARDS){if(y>h*.63f&&y<h*.73f){long day=System.currentTimeMillis()/(24*60*60*1000L),last=lastDailyClaim/(24*60*60*1000L);if(day>last){coins+=200;rockets++;lastDailyClaim=System.currentTimeMillis();save();show("Daily reward claimed!");}invalidate();}else if(y>h*.76f){mode=HOME;invalidate();}return true;}
        if(levelOver){if(y>h*.52f&&y<h*.60f){if(won)startLevel(Math.min(unlocked,level+1));else retryAfterLoss();}else if(y>h*.60f&&y<h*.69f){mode=SELECT;levelPage=(level-1)/20;invalidate();}return true;}
        float fy=boardTop+cell*N+dp(70);if(y>fy-dp(35)&&y<fy+dp(35)){if(x<w*.38f)selectedBooster=1;else if(x<w*.62f)selectedBooster=3;else selectedBooster=4;invalidate();return true;}if(y>fy+dp(45)&&y<fy+dp(125)){if(x<w/2){mode=SELECT;levelPage=(level-1)/20;}else startLevel(level);invalidate();return true;}
        int c=(int)((x-boardLeft)/cell),r=(int)((y-boardTop)/cell);if(r<0||r>=N||c<0||c>=N)return true;if(selectedBooster>0){useBooster(r,c);return true;}if(selR<0){selR=r;selC=c;invalidate();return true;}if(Math.abs(selR-r)+Math.abs(selC-c)==1){swap(selR,selC,r,c);if(hasMatch()){moves--;resolve(r,c);afterMove();}else{swap(selR,selC,r,c);show("No match");}selR=selC=-1;invalidate();}else{selR=r;selC=c;invalidate();}return true;}
    private void retryAfterLoss(){if(lives<=0){mode=HOME;show("No lives available");invalidate();return;}lives--;lastLifeAt=System.currentTimeMillis();save();startLevel(level);}
    private void useBooster(int r,int c){if(selectedBooster==1&&rockets>0){rockets--;power[r][c]=1;}else if(selectedBooster==3&&bombs>0){bombs--;power[r][c]=3;}else if(selectedBooster==4&&rainbows>0){rainbows--;power[r][c]=4;}else{show("No booster left");selectedBooster=0;return;}selectedBooster=0;save();show("Booster placed");invalidate();}
    private void resolve(int pr,int pc){int chain=0;while(true){boolean[][] m=matches();int n=count(m);if(n==0)break;chain++;if(chain==1)createSpecial(m,pr,pc);expandSpecials(m);n=count(m);score+=n*50*chain;dailyMatches+=n/3;for(int r=0;r<N;r++)for(int c=0;c<N;c++)if(m[r][c]&&blocker[r][c]>0){int type=blocker[r][c]/10,hp=blocker[r][c]%10;hp--;blocker[r][c]=hp>0?type*10+hp:0;}drop(m);}if(chain>1)show("Cascade x"+chain+"!");}
    private void createSpecial(boolean[][] m,int pr,int pc){if(pr<0||!m[pr][pc])return;int color=board[pr][pc],h=1,v=1;for(int c=pc-1;c>=0&&board[pr][c]==color;c--)h++;for(int c=pc+1;c<N&&board[pr][c]==color;c++)h++;for(int r=pr-1;r>=0&&board[r][pc]==color;r--)v++;for(int r=pr+1;r<N&&board[r][pc]==color;r++)v++;int q=h>=5||v>=5?4:(h>=3&&v>=3?3:(h>=4?1:(v>=4?2:0)));if(q>0){m[pr][pc]=false;power[pr][pc]=q;}}
    private void expandSpecials(boolean[][] m){boolean again=true;while(again){again=false;for(int r=0;r<N;r++)for(int c=0;c<N;c++)if(m[r][c]&&power[r][c]>0){int q=power[r][c];power[r][c]=0;again=true;if(q==1)for(int x=0;x<N;x++)m[r][x]=true;else if(q==2)for(int y=0;y<N;y++)m[y][c]=true;else if(q==3)for(int y=Math.max(0,r-1);y<=Math.min(N-1,r+1);y++)for(int x=Math.max(0,c-1);x<=Math.min(N-1,c+1);x++)m[y][x]=true;else{int col=board[r][c];for(int y=0;y<N;y++)for(int x=0;x<N;x++)if(board[y][x]==col)m[y][x]=true;}}}}
    private void afterMove(){LevelCatalog.Spec s=LevelCatalog.get(level);if(score>=s.targetScore&&obstacles()==0){won=true;levelOver=true;coins+=100;stars++;wins++;dailyWins++;unlocked=Math.min(LevelCatalog.MAX_LEVEL,Math.max(unlocked,level+1));if(wins%5==0)rockets++;save();vibrate(60);}else if(moves<=0){won=false;levelOver=true;save();}}
    private boolean[][] matches(){boolean[][] m=new boolean[N][N];for(int r=0;r<N;r++){int s=0;for(int c=1;c<=N;c++)if(c==N||board[r][c]!=board[r][s]){if(c-s>=3)for(int k=s;k<c;k++)m[r][k]=true;s=c;}}for(int c=0;c<N;c++){int s=0;for(int r=1;r<=N;r++)if(r==N||board[r][c]!=board[s][c]){if(r-s>=3)for(int k=s;k<r;k++)m[k][c]=true;s=r;}}return m;}
    private boolean hasMatch(){return count(matches())>0;}private int count(boolean[][] m){int n=0;for(int r=0;r<N;r++)for(int c=0;c<N;c++)if(m[r][c])n++;return n;}private int obstacles(){int n=0;for(int r=0;r<N;r++)for(int c=0;c<N;c++)if(blocker[r][c]>0)n++;return n;}
    private void drop(boolean[][] m){for(int c=0;c<N;c++){int wr=N-1;for(int r=N-1;r>=0;r--)if(!m[r][c]){board[wr][c]=board[r][c];power[wr][c]=power[r][c];blocker[wr][c]=blocker[r][c];wr--;}while(wr>=0){board[wr][c]=rng.nextInt(TYPES);power[wr][c]=0;blocker[wr][c]=0;wr--;}}}
    private void swap(int r1,int c1,int r2,int c2){int t=board[r1][c1];board[r1][c1]=board[r2][c2];board[r2][c2]=t;t=power[r1][c1];power[r1][c1]=power[r2][c2];power[r2][c2]=t;t=blocker[r1][c1];blocker[r1][c1]=blocker[r2][c2];blocker[r2][c2]=t;}
    private void claimQuest(float y,int h){int reward=0;if(y>h*.15f&&y<h*.27f&&dailyWins>=3){reward=150;dailyWins=0;}else if(y>h*.29f&&y<h*.41f&&dailyMatches>=25){rockets++;dailyMatches=0;show("Rocket booster claimed");}else if(y>h*.43f&&y<h*.55f&&renovations>=5&&!prefs.getBoolean("q_reno",false)){bombs++;prefs.edit().putBoolean("q_reno",true).apply();show("Bomb booster claimed");}else if(y>h*.57f&&y<h*.69f&&wins>=20&&!prefs.getBoolean("q_wins",false)){rainbows++;prefs.edit().putBoolean("q_wins",true).apply();show("Rainbow booster claimed");}if(reward>0){coins+=reward;show("+"+reward+" coins claimed");}save();invalidate();}
    private void save(){prefs.edit().putInt("level",unlocked).putInt("coins",coins).putInt("stars",stars).putInt("lives",lives).putInt("wins",wins).putInt("renovations",renovations).putInt("rocketBoosters",rockets).putInt("bombBoosters",bombs).putInt("rainbowBoosters",rainbows).putInt("dailyWins",dailyWins).putInt("dailyMatches",dailyMatches).putLong("lastLifeAt",lastLifeAt).putLong("lastDailyClaim",lastDailyClaim).apply();}
    private void show(String s){banner=s;bannerUntil=System.currentTimeMillis()+1900;invalidate();}
    private void vibrate(long ms){try{if(vibrator==null)return;if(android.os.Build.VERSION.SDK_INT>=26)vibrator.vibrate(VibrationEffect.createOneShot(ms,VibrationEffect.DEFAULT_AMPLITUDE));else vibrator.vibrate(ms);}catch(Exception ignored){}}
    private float dp(float v){return v*getResources().getDisplayMetrics().density;}
}
